(function(g){var window=this;var gAa=function(a,b){return g.Rb(a,b)},Y5=function(a){g.Fm(a,"zx",g.wb());
return a},Z5=function(a,b,c){g.xa(c)||(c=[String(c)]);
g.Im(a.g,b,c)},hAa=function(a,b){var c=[];
g.jk(b,function(a){try{var b=g.ZC.prototype.l.call(this,a,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.t(b)?g.YC(b)&&c.push(a):c.push(a)},a);
return c},iAa=function(a,b){var c=hAa(a,b);
(0,g.C)(c,function(a){g.ZC.prototype.remove.call(this,a)},a)},jAa=function(){var a=g.EG;
iAa(a,a.g.ee(!0))},kAa=function(a,b,c,d){var e=new g.wm(null,void 0);
a&&g.xm(e,a);b&&g.ym(e,b);c&&g.zm(e,c);d&&g.Am(e,d);return e},lAa=function(a){g.OF[a]&&(a=g.OF[a],(0,g.C)(a,function(a){g.MF[a]&&delete g.MF[a]}),a.length=0)},mAa=function(a){var b=g.LF();
if(b)if(b.clear(a),a)lAa(a);else for(var c in g.OF)lAa(c)},$5=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.o=!1;this.capabilities=new window.Set;this.experiments=new window.Set;this.theme="u";new g.qm;this.g=this.l="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",nAa(this,a.capabilities||""),oAa(this,a.experiments||""),this.l=a.remoteControllerUrl||"",
this.g=a.localChannelEncryptionKey||"")},nAa=function(a,b){a.capabilities.clear();
(0,g.Fd)(b.split(","),g.Da(gAa,pAa)).forEach(function(b){a.capabilities.add(b)})},oAa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(b){a.experiments.add(b)})},a6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},b6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},qAa=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},rAa=function(a){return new a6(a)},sAa=function(a){return g.xa(a)?(0,g.H)(a,rAa):[]},c6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},d6=function(a){return g.xa(a)?"["+(0,g.H)(a,c6).join(",")+"]":"null"},e6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},tAa=function(a){return(0,g.H)(a,function(a){return{key:a.id,
name:a.name}})},f6=function(a,b){return g.Ia(a,function(a){return a||b?!a!=!b?!1:a.id==b.id:!0})},g6=function(a,b){return g.Ia(a,function(a){return b6(a,b)})},h6=function(){var a=g.HG("yt-remote-connected-devices")||[];
g.eb(a);return a},uAa=function(a){if(g.Na(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.H)(a,function(a,b){return 0==b?a:a.substring(c.length)})},vAa=function(a){g.GG("yt-remote-connected-devices",a,86400)},j6=function(){if(i6)return i6;
var a=g.HG("yt-remote-device-id");a||(a=e6(),g.GG("yt-remote-device-id",a,31536E3));for(var b=h6(),c=1,d=a;g.Ma(b,d);)c++,d=a+"#"+c;return i6=d},k6=function(){var a=h6(),b=j6();
g.Ma(a,b);g.MG()&&g.gb(a,b);a=uAa(a);if(g.Na(a))try{g.KG.remove("remote_sid","/","youtube.com")}catch(c){}else try{g.LG("remote_sid",a.join(","),-1)}catch(c){}},wAa=function(){return g.HG("yt-remote-session-browser-channel")},xAa=function(){return g.HG("yt-remote-local-screens")||[]},yAa=function(){g.GG("yt-remote-lounge-token-expiration",!0,86400)},zAa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.H)(xAa(),function(a){return a.loungeToken}),c=(0,g.H)(a,function(a){return a.loungeToken});
(0,g.fm)(c,function(a){return!g.Ma(b,a)})&&yAa();
g.GG("yt-remote-local-screens",a,31536E3)},AAa=function(a,b){g.GG("yt-remote-session-browser-channel",a);
g.GG("yt-remote-session-screen-id",b);var c=h6(),d=j6();g.Ma(c,d)||c.push(d);vAa(c);k6()},l6=function(a){a||(g.IG("yt-remote-session-screen-id"),g.IG("yt-remote-session-video-id"));
k6();a=h6();g.Ra(a,j6());vAa(a)},BAa=function(){if(!m6){var a=g.eD();
a&&(m6=new g.TC(a))}return m6?!!m6.get("yt-remote-use-staging-server"):!1},CAa=function(){var a=window.document.createElement("a");
g.Uc(a,"https://www.gstatic.com/cv/js/sender/v1/cast_sender.js");a=a.href.replace(/^[a-zA-Z]+:\/\//,"//");return"js-"+g.Ab(a)},DAa=function(a,b){var c=g.xd("SCRIPT");
c.id=a;c.onload=function(){b&&(0,window.setTimeout)(b,0)};
c.onreadystatechange=function(){switch(c.readyState){case "loaded":case "complete":c.onload()}};
g.Vc(c,g.Yd("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"));var d=window.document.getElementsByTagName("head")[0]||window.document.body;d.insertBefore(c,d.firstChild);return c},EAa=function(){var a=CAa(),b=window.document.getElementById(a),c=b&&g.$E(b,"loaded");
c||b&&!c||(b=DAa(a,function(){g.$E(b,"loaded")||(g.ZE(b,"loaded","true"),g.SF(a),g.ND(g.Da(mAa,a),0))}))},n6=function(a){return!!window.document.currentScript&&(-1!=window.document.currentScript.src.indexOf("?"+a)||-1!=window.document.currentScript.src.indexOf("&"+a))},FAa=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},o6=function(a){a.length?GAa(a.shift(),function(){o6(a)}):p6()},HAa=function(a){return"chrome-extension://"+a+q6},GAa=function(a,
b,c){var d=window.document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(window.document.head||window.document.documentElement).appendChild(d)},r6=function(a){return 0<=window.navigator.userAgent.indexOf(a)},p6=function(){var a=FAa();
a&&a(!1,"No cast extension found")},s6=function(){if(IAa){var a=2,b=FAa(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;GAa("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",p6,c)}},JAa=function(){var a=window.__gCrWeb&&window.__gCrWeb.message&&window.__gCrWeb.message.invokeOnHost;
a&&(s6(),a({command:"cast.sender.init"}))},KAa=function(){s6();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);o6(["//www.gstatic.com/eureka/clank/"+(a?(0,window.parseInt)(a[1],10):0)+q6,"//www.gstatic.com/eureka/clank"+q6])},t6=function(a,b,c){g.K.call(this);
this.C=null!=c?(0,g.z)(a,c):a;this.uc=b;this.B=(0,g.z)(this.cI,this);this.g=!1;this.l=0;this.o=this.xa=null;this.A=[]},u6=function(){},v6=function(a,b,c,d){this.g=a;
this.o=b;this.F=c;this.D=d||1;this.B=45E3;this.A=new g.Mm(this);this.l=new g.pg;this.l.setInterval(250)},MAa=function(a,b,c){a.rj=1;
a.mh=Y5(b.clone());a.Ii=c;a.C=!0;LAa(a,null)},w6=function(a,b,c,d,e){a.rj=1;
a.mh=Y5(b.clone());a.Ii=null;a.C=c;e&&(a.zC=!1);LAa(a,d)},LAa=function(a,b){a.Uj=(0,g.G)();
x6(a);a.Eh=a.mh.clone();Z5(a.Eh,"t",a.D);a.Ul=0;a.Pc=a.g.Qq(a.g.Nl()?b:null);0<a.xr&&(a.Zo=new g.Pk((0,g.z)(a.OD,a,a.Pc),a.xr));a.A.R(a.Pc,"readystatechange",a.gT);var c=a.ji?g.Yb(a.ji):{};a.Ii?(a.Ip="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.Pc.send(a.Eh,a.Ip,a.Ii,c)):(a.Ip="GET",a.zC&&!g.td&&(c.Connection="close"),a.Pc.send(a.Eh,a.Ip,null,c));a.g.tf(1)},PAa=function(a,b,c){for(var d=!0;!a.Sh&&a.Ul<c.length;){var e=NAa(a,c);
if(e==y6){4==b&&(a.nh=4,z6(15),d=!1);break}else if(e==OAa){a.nh=4;z6(16);d=!1;break}else A6(a,e)}4==b&&0==c.length&&(a.nh=1,z6(17),d=!1);a.xf=a.xf&&d;d||(B6(a),C6(a))},NAa=function(a,b){var c=a.Ul,d=b.indexOf("\n",c);
if(-1==d)return y6;c=Number(b.substring(c,d));if((0,window.isNaN)(c))return OAa;d+=1;if(d+c>b.length)return y6;var e=b.substr(d,c);a.Ul=d+c;return e},RAa=function(a,b){a.Uj=(0,g.G)();
x6(a);var c=b?window.location.hostname:"";a.Eh=a.mh.clone();g.Fm(a.Eh,"DOMAIN",c);g.Fm(a.Eh,"t",a.D);try{a.yf=new window.ActiveXObject("htmlfile")}catch(n){B6(a);a.nh=7;z6(22);C6(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in D6)k=D6[l];else if(l in QAa)k=D6[l]=QAa[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=
m.toString(16).toUpperCase()}k=D6[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}d+="</body></html>";c=g.Wc(g.rc("b/12014412"),d);a.yf.open();a.yf.write(g.Mc(c));a.yf.close();a.yf.parentWindow.m=(0,g.z)(a.kS,a);a.yf.parentWindow.d=(0,g.z)(a.QB,a,!0);a.yf.parentWindow.rpcClose=(0,g.z)(a.QB,a,!1);c=a.yf.createElement("DIV");a.yf.parentWindow.document.body.appendChild(c);d=g.Dc(a.Eh.toString());d=g.ob(g.Ac(d));d=g.Wc(g.rc("b/12014412"),'<iframe src="'+d+'"></iframe>');c.innerHTML=g.Mc(d);
a.g.tf(1)},x6=function(a){a.fv=(0,g.G)()+a.B;
SAa(a,a.B)},SAa=function(a,b){if(null!=a.pk)throw Error("WatchDog timer not null");
a.pk=E6((0,g.z)(a.BS,a),b)},F6=function(a){a.pk&&(g.w.clearTimeout(a.pk),a.pk=null)},C6=function(a){a.g.Zx()||a.Sh||a.g.No(a)},B6=function(a){F6(a);
g.We(a.Zo);a.Zo=null;a.l.stop();g.Sm(a.A);if(a.Pc){var b=a.Pc;a.Pc=null;b.abort();b.dispose()}a.yf&&(a.yf=null)},A6=function(a,b){try{a.g.JB(a,b),a.g.tf(4)}catch(c){}},UAa=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;TAa(a,b,function(e){e?c(!0):g.w.setTimeout(function(){UAa(a,b,c,d,f)},f)})}},TAa=function(a,b,c){var d=new window.Image;
d.onload=function(){try{G6(d),c(!0)}catch(e){}};
d.onerror=function(){try{G6(d),c(!1)}catch(e){}};
d.onabort=function(){try{G6(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{G6(d),c(!1)}catch(e){}};
g.w.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
d.src=a},G6=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},VAa=function(a){this.g=a;
this.l=new u6},WAa=function(a){var b=H6(a.g,a.tk,"/mail/images/cleardot.gif");
Y5(b);UAa(b.toString(),5E3,(0,g.z)(a.oH,a),3,2E3);a.tf(1)},J6=function(a){var b=a.g.H;
if(null!=b)z6(5),b?(z6(11),I6(a.g,a,!1)):(z6(12),I6(a.g,a,!0));else if(a.se=new v6(a,void 0,void 0,void 0),a.se.ji=a.ur,b=a.g,b=H6(b,b.Nl()?a.Qk:null,a.wr),z6(5),!g.rd||g.nc(10))Z5(b,"TYPE","xmlhttp"),w6(a.se,b,!1,a.Qk,!1);else{Z5(b,"TYPE","html");var c=a.se;a=!!a.Qk;c.rj=3;c.mh=Y5(b.clone());RAa(c,a)}},K6=function(a,b,c){this.g=1;
this.l=[];this.A=[];this.B=new u6;this.F=a||null;this.H=null!=b?b:null;this.C=c||!1},XAa=function(a,b){this.g=a;
this.map=b;this.context=null},YAa=function(a){g.Ye.call(this,"statevent",a)},ZAa=function(a,b){g.Ye.call(this,"timingevent",a);
this.size=b},$Aa=function(a){g.Ye.call(this,"serverreachability",a)},cBa=function(a){aBa(a);
if(3==a.g){var b=a.zl++,c=a.Dn.clone();g.Fm(c,"SID",a.o);g.Fm(c,"RID",b);g.Fm(c,"TYPE","terminate");L6(a,c);b=new v6(a,a.o,b,void 0);b.rj=2;b.mh=Y5(c.clone());(new window.Image).src=b.mh;b.Uj=(0,g.G)();x6(b)}bBa(a)},dBa=function(a){a.JH(1,0);
a.Dn=H6(a,null,a.tr);M6(a)},aBa=function(a){a.dh&&(a.dh.abort(),a.dh=null);
a.tc&&(a.tc.cancel(),a.tc=null);a.qg&&(g.w.clearTimeout(a.qg),a.qg=null);N6(a);a.Qd&&(a.Qd.cancel(),a.Qd=null);a.fh&&(g.w.clearTimeout(a.fh),a.fh=null)},eBa=function(a,b){if(0==a.g)throw Error("Invalid operation: sending map when state is closed");
a.l.push(new XAa(a.fO++,b));2!=a.g&&3!=a.g||M6(a)},M6=function(a){a.Qd||a.fh||(a.fh=E6((0,g.z)(a.OB,a),0),a.jj=0)},gBa=function(a,b){if(1==a.g){if(!b){a.zl=Math.floor(1E5*Math.random());
var c=a.zl++,d=new v6(a,"",c,void 0);d.ji=null;var e=O6(a),f=a.Dn.clone();g.Fm(f,"RID",c);g.Fm(f,"CVER","1");L6(a,f);MAa(d,f,e);a.Qd=d;a.g=2}}else 3==a.g&&(b?fBa(a,b):0==a.l.length||a.Qd||fBa(a))},fBa=function(a,b){if(b)if(6<a.Uh){a.l=a.A.concat(a.l);
a.A.length=0;var c=a.zl-1;var d=O6(a)}else c=b.F,d=b.Ii;else c=a.zl++,d=O6(a);var e=a.Dn.clone();g.Fm(e,"SID",a.o);g.Fm(e,"RID",c);g.Fm(e,"AID",a.Ej);L6(a,e);c=new v6(a,a.o,c,a.jj+1);c.ji=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.Qd=c;MAa(c,e,d)},L6=function(a,b){if(a.qd){var c=a.qd.Hx();
c&&g.Ib(c,function(a,c){g.Fm(b,c,a)})}},O6=function(a){var b=Math.min(a.l.length,1E3),c=["count="+b];
if(6<a.Uh&&0<b){var d=a.l[0].g;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.l[e].g,k=a.l[e].map;f=6>=a.Uh?e:f-d;try{g.Ib(k,function(a,b){c.push("req"+f+"_"+b+"="+(0,window.encodeURIComponent)(a))})}catch(l){c.push("req"+f+"_type="+(0,window.encodeURIComponent)("_badmap"))}}a.A=a.A.concat(a.l.splice(0,b));
return c.join("&")},hBa=function(a){a.tc||a.qg||(a.D=1,a.qg=E6((0,g.z)(a.NB,a),0),a.Yi=0)},P6=function(a){if(a.tc||a.qg||3<=a.Yi)return!1;
a.D++;a.qg=E6((0,g.z)(a.NB,a),iBa(a,a.Yi));a.Yi++;return!0},I6=function(a,b,c){a.Hp=c;
a.hf=b.yg;a.C||dBa(a)},N6=function(a){null!=a.Wh&&(g.w.clearTimeout(a.Wh),a.Wh=null)},iBa=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},Q6=function(a,b){if(2==b||9==b){var c=null;
a.qd&&(c=null);var d=(0,g.z)(a.bU,a);c||(c=new g.wm("//www.google.com/images/cleardot.gif"),Y5(c));TAa(c.toString(),1E4,d)}else z6(2);jBa(a,b)},jBa=function(a,b){a.g=0;
a.qd&&a.qd.Cw(b);bBa(a);aBa(a)},bBa=function(a){a.g=0;
a.hf=-1;if(a.qd)if(0==a.A.length&&0==a.l.length)a.qd.Fq();else{g.Va(a.A);var b=g.Va(a.l);a.A.length=0;a.l.length=0;a.qd.Fq(b)}},H6=function(a,b,c){var d=g.Gm(c);
if(""!=d.l)b&&g.ym(d,b+"."+d.l),g.zm(d,d.B);else{var e=window.location;d=kAa(e.protocol,b?b+"."+e.hostname:e.hostname,e.port,c)}a.Dk&&g.Ib(a.Dk,function(a,b){g.Fm(d,b,a)});
g.Fm(d,"VER",a.Uh);L6(a,d);return d},E6=function(a,b){if(!g.za(a))throw Error("Fn must not be null and must be a function");
return g.w.setTimeout(function(){a()},b)},z6=function(a){R6.dispatchEvent(new YAa(R6,a))},kBa=function(){},lBa=function(a,b){this.action=a;
this.params=b||{}},T6=function(a,b){g.K.call(this);
this.g=new g.Zt(this.o,0,this);g.M(this,this.g);this.l=this.uc=0;if(g.za(a))b&&(a=(0,g.z)(a,b));else if(a&&g.za(a.handleEvent))a=(0,g.z)(a.handleEvent,a);else throw Error("Invalid listener argument");this.A=a;S6(this)},S6=function(a){a.g.stop();
a.uc=5E3+2E4*Math.random()},U6=function(a,b,c){this.K=a;
this.C=b;this.o=new g.SC;this.l=new T6(this.GU,this);this.g=this.Za=null;this.I=!1;this.B=null;this.H="";this.F=this.A=0;this.D=[];this.L=c||!1},mBa=function(a){return{firstTestResults:[""],
secondTestResults:!a.g.Hp,sessionId:a.g.o,arrayId:a.g.Ej}},nBa=function(a,b){a.F=b||0;
a.l.stop();a.g&&(3==a.g.g&&gBa(a.g),cBa(a.g));a.F=0},V6=function(a){return!!a.g&&3==a.g.g},oBa=function(a,b){(a.C.loungeIdToken=b)||a.l.stop()},W6=function(a){this.port=this.domain="";
this.g="/api/lounge";this.l=!0;a=a||window.document.location.href;var b=g.Gg(a)||"";b&&(this.port=":"+b);this.domain=g.Fg(a)||"";a=g.Gb;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.zb(a,"10.0")&&(this.l=!1))},X6=function(a,b){var c=a.g;
if(g.t(void 0)?0:a.l)c="https://"+a.domain+a.port+a.g;return g.Pg(c+b,{})},Y6=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,Hb:g.Da(a.A,d,!0),onError:g.Da(a.o,e),ud:g.Da(a.B,e)};c&&(a.Lb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.kE(b,a)},sBa=function(){var a=pBa;
qBa();Z6.push(a);rBa(Z6)},$6=function(a,b){qBa();
var c=Z6,d=tBa(a,String(b));g.Na(c)?uBa(d):(rBa(c),(0,g.C)(c,function(a){a(d)}))},qBa=function(){Z6||(Z6=g.x("yt.mdx.remote.debug.handlers_")||[],g.ua("yt.mdx.remote.debug.handlers_",Z6,void 0))},uBa=function(a){var b=(a7+1)%50;
a7=b;b7[b]=a;c7||(c7=49==b)},rBa=function(a){var b=b7;
if(b[0]){var c=a7,d=c7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.C)(a,function(a){a(e)})}while(d!=c);
b7=Array(50);a7=-1;c7=!1}},tBa=function(a,b){var c=((0,g.G)()-vBa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},d7=function(a){g.EF.call(this);
this.D=a;this.g=[]},wBa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.g.push(b);return!0},xBa=function(a,b){var c=a.g.length!=b.length;
a.g=(0,g.Fd)(a.g,function(a){return!!f6(b,a)});
for(var d=0,e=b.length;d<e;d++)c=wBa(a,b[d])||c;return c},yBa=function(a,b){var c=a.g.length;
a.g=(0,g.Fd)(a.g,function(a){return!(a||b?!a!=!b?0:a.id==b.id:1)});
return a.g.length<c},e7=function(a,b,c,d){g.EF.call(this);
this.C=a;this.B=b;this.o=c;this.A=d;this.l=0;this.g=null;this.xa=window.NaN},g7=function(a){d7.call(this,"LocalScreenService");
this.o=a;this.l=window.NaN;f7(this);this.info("Initializing with "+d6(this.g))},zBa=function(a){if(a.g.length){var b=(0,g.H)(a.g,function(a){return a.id}),c=X6(a.o,"/pairing/get_lounge_token_batch");
Y6(a.o,c,{screen_ids:b.join(",")},(0,g.z)(a.oI,a),(0,g.z)(a.nI,a))}},f7=function(a){var b=sAa(xAa());
b=(0,g.Fd)(b,function(a){return!a.uuid});
return xBa(a,b)},h7=function(a,b){zAa((0,g.H)(a.g,qAa));
b&&yAa()},j7=function(a,b){g.EF.call(this);
this.C=b;var c=g.HG("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.C(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.Ma(c,l)}this.g=d;this.B=a;this.o=this.A=window.NaN;this.l=null;i7("Initialized with "+g.wg(this.g))},ABa=function(a,b,c){var d=X6(a.B,"/pairing/get_screen_availability");
Y6(a.B,d,{lounge_token:b.token},(0,g.z)(function(a){a=a.screens||[];for(var d=0,e=a.length;d<e;++d)if(a[d].loungeToken==b.token){c("online"==a[d].status);return}c(!1)},a),(0,g.z)(function(){c(!1)},a))},k7=function(a,b){a:if(g.Mb(b)!=g.Mb(a.g))var c=!1;
else{c=g.Ob(b);for(var d=0,e=c.length;d<e;++d)if(!a.g[c[d]]){c=!1;break a}c=!0}c||(i7("Updated online screens: "+g.wg(a.g)),a.g=b,a.P("screenChange"));BBa(a)},l7=function(a){(0,window.isNaN)(a.o)||g.PD(a.o);
a.o=g.ND((0,g.z)(a.ru,a),0<a.A&&a.A<(0,g.G)()?2E4:1E4)},i7=function(a){$6("OnlineScreenService",a)},CBa=function(a){var b={};
(0,g.C)(a.C(),function(a){a.token?b[a.token]=a.id:this.fc("Requesting availability of screen w/o lounge token.")});
return b},BBa=function(a){a=g.Ob(g.Jb(a.g,function(a){return a}));
g.eb(a);a.length?g.GG("yt-remote-online-screen-ids",a.join(","),60):g.IG("yt-remote-online-screen-ids")},m7=function(a){d7.call(this,"ScreenService");
this.C=a;this.l=this.o=null;this.A=[];this.B={};DBa(this)},FBa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.B[b]);var k=a.ke();if(k=(c?g6(k,c):null)||g6(k,b)){k.uuid=b;var l=n7(a,k);ABa(a.l,l,function(a){e(a?l:null)})}else c?EBa(a,c,(0,g.z)(function(a){var f=n7(this,new a6({name:d,
screenId:c,loungeToken:a,dialId:b||""}));ABa(this.l,f,function(a){e(a?f:null)})},a),f):e(null)},GBa=function(a,b){for(var c=0,d=a.g.length;c<d;++c)if(a.g[c].name==b)return a.g[c];
return null},EBa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={Lb:{screen_ids:b},method:"POST",context:a,Hb:function(a,e){var f=e&&e.screens||[];f[0]&&f[0].screenId==b?c(f[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.kE(X6(a.C,"/pairing/get_lounge_token_batch"),e)},HBa=function(a){a.g=a.o.ke();
var b=a.B,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.g.length;b<d;++b){var e=a.g[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+d6(a.g))},DBa=function(a){o7(a);
a.o=new g7(a.C);a.o.subscribe("screenChange",(0,g.z)(a.EI,a));HBa(a);a.A=sAa(g.HG("yt-remote-automatic-screen-cache")||[]);o7(a);a.info("Initializing automatic screens: "+d6(a.A));a.l=new j7(a.C,(0,g.z)(a.ke,a,!0));a.l.subscribe("screenChange",(0,g.z)(function(){this.P("onlineScreenChange")},a))},n7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=g6(a.A,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.A.push(b),g.GG("yt-remote-automatic-screen-cache",(0,g.H)(a.A,qAa)));o7(a);a.B[b.uuid]=b.id;g.GG("yt-remote-device-id-map",a.B,31536E3);return b},o7=function(a){a.B=g.HG("yt-remote-device-id-map")||{}},p7=function(a,b,c){g.EF.call(this);
this.L=c;this.H=a;this.l=b;this.o=null},q7=function(a,b){$6(a.L,b)},r7=function(a,b){p7.call(this,a,b,"CastSession");
this.g=null;this.A=0;this.C=(0,g.z)(this.MU,this);this.B=(0,g.z)(this.LS,this);this.A=g.ND((0,g.z)(function(){IBa(this,null)},this),12E4)},JBa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.wg(void 0));
var b={type:"getMdxSessionStatus"};a.g?a.g.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.y,(0,g.z)(function(){q7(this,"Failed to send message: getMdxSessionStatus.")},a)):q7(a,"Sending yt message without session: "+g.wg(b))},IBa=function(a,b){g.PD(a.A);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.o||a.o.id!=b){var c=(0,g.z)(a.Oo,a),d=(0,g.z)(a.qe,a);a.Sx(b,c,d,5)}}else a.qe(Error("Waiting for session status timed out."))},s7=function(a,b,c){p7.call(this,a,b,"DialSession");
this.A=this.F=null;this.I="";this.N=c;this.B=null;this.D=g.y;this.C=window.NaN;this.K=(0,g.z)(this.PU,this);this.g=g.y},KBa=function(a){a.g=a.H.VD(a.I,a.l.label,a.l.friendlyName,(0,g.z)(function(a){this.g=g.y;
this.Oo(a)},a),(0,g.z)(function(a){this.g=g.y;
this.qe(a)},a))},LBa=function(a){var b={};
b.pairingCode=a.I;b.theme=a.N;if(a.B){var c=a.B.currentTime||0;b.v=a.B.videoId;b.t=c}BAa()&&(b.env_useStageMdx=1);return g.Ng(b)},t7=function(a,b){p7.call(this,a,b,"ManualSession");
this.g=g.ND((0,g.z)(this.Fj,this,null),150)},u7=function(a,b,c,d){g.EF.call(this);
this.l=a;this.D=b||"233637DE";this.C=c||"cl";this.F=d||!1;this.g=null;this.B=!1;this.o=[];this.A=(0,g.z)(this.rR,this)},MBa=function(a,b){return b?g.Ia(a.o,function(a){return b6(b,a.label)},a):null},v7=function(a){$6("Controller",a)},pBa=function(a){window.chrome&&window.chrome.cast&&window.chrome.cast.logMessage&&window.chrome.cast.logMessage(a)},w7=function(a){return a.B||!!a.o.length||!!a.g},x7=function(a,b,c){b!=a.g&&(g.We(a.g),(a.g=b)?(c?a.P("yt-remote-cast2-receiver-resumed",b.l):a.P("yt-remote-cast2-receiver-selected",
b.l),b.subscribe("sessionScreen",(0,g.z)(a.LB,a,b)),b.o?a.P("yt-remote-cast2-session-change",b.o):c&&a.g.Fj(null)):a.P("yt-remote-cast2-session-change",null))},NBa=function(a){var b=a.l.UD(),c=a.g&&a.g.l;
a=(0,g.H)(b,function(a){c&&b6(a,c.label)&&(c=null);var b=a.uuid?a.uuid:a.id,d=MBa(this,a);d?(d.label=b,d.friendlyName=a.name):(d=new window.chrome.cast.Receiver(b,a.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM);return d},a);
c&&(c.receiverType!=window.chrome.cast.ReceiverType.CUSTOM&&(c=new window.chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=window.chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},TBa=function(a,b,c,d,e,f,k){OBa()?PBa(b,e,f,k)&&(z7(!0),window.chrome&&window.chrome.cast&&window.chrome.cast.isAvailable?QBa(a,c):(window.__onGCastApiAvailable=function(b,d){b?QBa(a,c):(A7("Failed to load cast API: "+d),B7(!1),z7(!1),g.IG("yt-remote-cast-available"),g.IG("yt-remote-cast-receiver"),RBa(),
c(!1))},d?window.spf?window.spf.script.load("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js","",void 0):EAa():r6("CriOS")?JAa():r6("Android")&&r6("Chrome/")&&window.navigator.presentation?KAa():window.chrome&&window.navigator.presentation&&!r6("Edge")?(s6(),o6(SBa.map(HAa))):p6())):y7("Cannot initialize because not running Chrome")},RBa=function(){y7("dispose");
var a=C7();a&&a.dispose();g.ua("yt.mdx.remote.cloudview.instance_",null,void 0);UBa(!1);g.QF(D7);D7.length=0},E7=function(){return!!g.HG("yt-remote-cast-installed")},VBa=function(){var a=g.HG("yt-remote-cast-receiver");
return a?a.friendlyName:null},WBa=function(){y7("clearCurrentReceiver");
g.IG("yt-remote-cast-receiver")},XBa=function(){return E7()?C7()?C7().getCastSession():(A7("getCastSelector: Cast is not initialized."),null):(A7("getCastSelector: Cast API is not installed!"),null)},G7=function(){E7()?C7()?F7()?(y7("Requesting cast selector."),C7().requestSession()):(y7("Wait for cast API to be ready to request the session."),D7.push(g.PF("yt-remote-cast2-api-ready",G7))):A7("requestCastSelector: Cast is not initialized."):A7("requestCastSelector: Cast API is not installed!")},H7=
function(a,b){F7()?C7().setConnectedScreenStatus(a,b):A7("setConnectedScreenStatus called before ready.")},OBa=function(){var a=0<=g.Gb.search(/ (CrMo|Chrome|CriOS)\//);
return g.KJ||a},YBa=function(a,b){C7().init(a,b)},PBa=function(a,b,c,d){var e=!1;
C7()||(a=new u7(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(a){g.GG("yt-remote-cast-available",a);g.TF("yt-remote-cast2-availability-change",a)}),a.subscribe("yt-remote-cast2-receiver-selected",function(a){y7("onReceiverSelected: "+a.friendlyName);
g.GG("yt-remote-cast-receiver",a);g.TF("yt-remote-cast2-receiver-selected",a)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(a){y7("onReceiverResumed: "+a.friendlyName);
g.GG("yt-remote-cast-receiver",a)}),a.subscribe("yt-remote-cast2-session-change",function(a){y7("onSessionChange: "+c6(a));
a||g.IG("yt-remote-cast-receiver");g.TF("yt-remote-cast2-session-change",a)}),g.ua("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
y7("cloudview.createSingleton_: "+e);return e},C7=function(){return g.x("yt.mdx.remote.cloudview.instance_")},QBa=function(a,b){B7(!0);
z7(!1);YBa(a,function(a){a?(UBa(!0),g.SF("yt-remote-cast2-api-ready")):(A7("Failed to initialize cast API."),B7(!1),g.IG("yt-remote-cast-available"),g.IG("yt-remote-cast-receiver"),RBa());b(a)})},y7=function(a){$6("cloudview",a)},A7=function(a){$6("cloudview",a)},B7=function(a){y7("setCastInstalled_ "+a);
g.GG("yt-remote-cast-installed",a)},F7=function(){return!!g.x("yt.mdx.remote.cloudview.apiReady_")},UBa=function(a){y7("setApiReady_ "+a);
g.ua("yt.mdx.remote.cloudview.apiReady_",a,void 0)},z7=function(a){g.ua("yt.mdx.remote.cloudview.initializing_",a,void 0)},I7=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.g=-1;this.muted=!1;this.audioTrackId=null;this.D=this.F=0;this.l=null;this.hasNext=this.Lf=!1;this.I=this.H=this.o=this.B=0;this.A=window.NaN;this.C=!1;this.reset(a)},J7=function(a){a.audioTrackId=null;
a.l=null;a.g=-1;a.Lf=!1;a.hasNext=!1;a.F=0;a.D=(0,g.G)();a.B=0;a.o=0;a.H=0;a.I=0;a.A=window.NaN;a.C=!1},K7=function(a){return a.kb()?((0,g.G)()-a.D)/1E3:0},L7=function(a,b){a.F=b;
a.D=(0,g.G)()},M7=function(a){switch(a.g){case 1:case 1081:return((0,g.G)()-a.D)/1E3+a.F;
case -1E3:return 0}return a.F},N7=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&J7(a)},O7=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.g;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.Zb(a.l);b.hasPrevious=a.Lf;b.hasNext=a.hasNext;b.playerTime=a.F;b.playerTimeAt=a.D;b.seekableStart=a.B;b.seekableEnd=a.o;b.duration=a.H;b.loadedTime=a.I;b.liveIngestionTime=a.A;return b},Q7=function(a,b){g.EF.call(this);
this.g=0;this.A=a;this.C=[];this.B=new g.iC;this.o=this.l=null;this.H=(0,g.z)(this.OO,this);this.D=(0,g.z)(this.Cl,this);this.F=(0,g.z)(this.NO,this);this.I=(0,g.z)(this.bP,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.ov,this),ZBa(this))):c=3;0!=c&&(b?this.ov(c):g.ND((0,g.z)(function(){this.ov(c)},this),0));
var d=XBa();d&&P7(this,d);this.subscribe("yt-remote-cast2-session-change",this.I)},R7=function(a){return new I7(a.A.getPlayerContextData())},ZBa=function(a){(0,g.C)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(a){this.C.push(this.A.subscribe(a,g.Da(this.nR,a),this))},a)},$Ba=function(a){(0,g.C)(a.C,function(a){this.A.unsubscribeByKey(a)},a);
a.C.length=0},S7=function(a,b){50>a.B.Lc()&&g.kC(a.B,b)},U7=function(a,b,c){var d=R7(a);
L7(d,c);-1E3!=d.g&&(d.g=b);T7(a,d)},V7=function(a,b,c){a.A.sendMessage(b,c)},T7=function(a,b){$Ba(a);
a.A.setPlayerContextData(O7(b));ZBa(a)},P7=function(a,b){a.o&&(a.o.removeUpdateListener(a.H),a.o.removeMediaListener(a.D),a.Cl(null));
a.o=b;a.o&&($6("CP","Setting cast session: "+a.o.sessionId),a.o.addUpdateListener(a.H),a.o.addMediaListener(a.D),a.o.media.length&&a.Cl(a.o.media[0]))},aCa=function(a){var b=a.l.media,c=a.l.customData;
if(b&&c){var d=R7(a);b.contentId!=d.videoId&&$6("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.g=c.playerState;L7(d,a.l.getEstimatedTime());T7(a,d)}else $6("CP","No cast media video. Ignoring state update.")},W7=function(a,b,c){return(0,g.z)(function(a){this.fc("Failed to "+b+" with cast v2 channel. Error code: "+a.code);
a.code!=window.chrome.cast.ErrorCode.TIMEOUT&&(this.fc("Retrying "+b+" using MDx browser channel."),V7(this,b,c))},a)},X7=function(a,b,c){g.EF.call(this);
this.B=window.NaN;this.N=!1;this.I=this.H=this.K=this.L=window.NaN;this.V=[];this.A=this.D=this.o=this.bb=this.g=null;this.na=a;this.V.push(g.oF(window,"beforeunload",(0,g.z)(this.fI,this)));this.l=[];this.bb=new I7;this.X=b.id;this.g=bCa(this,c);this.g.subscribe("handlerOpened",this.SO,this);this.g.subscribe("handlerClosed",this.PO,this);this.g.subscribe("handlerError",this.QO,this);this.g.subscribe("handlerMessage",this.RO,this);oBa(this.g,b.token);this.subscribe("remoteQueueChange",function(){var a=
this.bb.videoId;g.MG()&&g.GG("yt-remote-session-video-id",a)},this)},Y7=function(a){$6("conn",a)},bCa=function(a,b){return new U6(X6(a.na,"/bc"),b)},Z7=function(a,b){a.P("proxyStateChange",b)},cCa=function(a){a.B=g.ND((0,g.z)(function(){Y7("Connecting timeout");
this.C(1)},a),2E4)},$7=function(a){g.PD(a.B);
a.B=window.NaN},a8=function(a){g.PD(a.L);
a.L=window.NaN},dCa=function(a){b8(a);
a.K=g.ND((0,g.z)(function(){c8(this,"getNowPlaying")},a),2E4)},b8=function(a){g.PD(a.K);
a.K=window.NaN},fCa=function(a,b){b&&($7(a),a8(a));
b==(V6(a.g)&&(0,window.isNaN)(a.B))?b&&(Z7(a,1),c8(a,"getSubtitlesTrack")):b?(a.W()&&a.bb.reset(),Z7(a,1),c8(a,"getNowPlaying"),eCa(a)):a.C(1)},gCa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.bb.videoId&&(g.Ub(b.params)?a.bb.l=null:a.bb.l=b.params,a.P("remotePlayerChange"))},hCa=function(a,b){var c=b.params.videoId||b.params.video_id,d=(0,window.parseInt)(b.params.currentIndex,10);
a.bb.listId=b.params.listId||a.bb.listId;N7(a.bb,c,d);a.P("remoteQueueChange")},jCa=function(a,b){b.params=b.params||{};
hCa(a,b);iCa(a,b);a.P("autoplayDismissed")},iCa=function(a,b){var c=(0,window.parseInt)(b.params.currentTime||b.params.current_time,10);
L7(a.bb,(0,window.isNaN)(c)?0:c);c=(0,window.parseInt)(b.params.state,10);c=(0,window.isNaN)(c)?-1:c;-1==c&&-1E3==a.bb.g&&(c=-1E3);a.bb.g=c;c=Number(b.params.loadedTime);a.bb.I=(0,window.isNaN)(c)?0:c;c=Number(b.params.duration);a.bb.H=(0,window.isNaN)(c)?0:c;c=a.bb;var d=Number(b.params.liveIngestionTime);c.A=d;c.C=(0,window.isNaN)(d)?!1:!0;c=a.bb;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.B=(0,window.isNaN)(d)?0:d;c.o=(0,window.isNaN)(e)?0:e;1==a.bb.g?dCa(a):b8(a);
a.P("remotePlayerChange")},kCa=function(a,b){if(-1E3!=a.bb.g){var c=1085;
switch((0,window.parseInt)(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.bb.g=c;c=(0,window.parseInt)(b.params.currentTime,10);L7(a.bb,(0,window.isNaN)(c)?0:c);a.P("remotePlayerChange")}},lCa=function(a,b){var c="true"==b.params.muted;
a.bb.volume=(0,window.parseInt)(b.params.volume,10);a.bb.muted=c;a.P("remotePlayerChange")},mCa=function(a,b){a.D=b.params.videoId;
a.P("nowAutoplaying",(0,window.parseInt)(b.params.timeout,10))},nCa=function(a,b){var c="true"==b.params.hasNext;
a.bb.Lf="true"==b.params.hasPrevious;a.bb.hasNext=c;a.P("previousNextChange")},eCa=function(a){g.PD(a.I);
a.I=g.ND((0,g.z)(a.C,a,1),864E5)},c8=function(a,b,c){c?Y7("Sending: action="+b+", params="+g.wg(c)):Y7("Sending: action="+b);
a.g.sendMessage(b,c)},d8=function(a){d7.call(this,"ScreenServiceProxy");
this.dd=a;this.l=[];this.l.push(this.dd.$_s("screenChange",(0,g.z)(this.KU,this)));this.l.push(this.dd.$_s("onlineScreenChange",(0,g.z)(this.OQ,this)))},sCa=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.HD("MDX_CONFIG")||b;g.EG&&jAa();k6();e8||(e8=new W6(b?b.loungeApiHost:void 0),BAa()&&(e8.g="/api/loungedev"));f8||(f8=g.x("yt.mdx.remote.deferredProxies_")||[],g.ua("yt.mdx.remote.deferredProxies_",f8,void 0));oCa();var c=g8();if(!c){var d=new m7(e8);g.ua("yt.mdx.remote.screenService_",d,void 0);c=g8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);TBa(a,d,function(a){a?h8()&&H7(h8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){g.TF("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.x("yt.mdx.remote.initialized_")&&(g.ua("yt.mdx.remote.initialized_",!0,void 0),i8("Initializing: "+g.wg(b)),j8.push(g.PF("yt-remote-cast2-availability-change",function(){g.TF("yt-remote-receiver-availability-change")})),j8.push(g.PF("yt-remote-cast2-receiver-selected",function(){k8(null);
g.TF("yt-remote-auto-connect","cast-selector-receiver")})),j8.push(g.PF("yt-remote-cast2-receiver-resumed",function(){g.TF("yt-remote-receiver-resumed","cast-selector-receiver")})),j8.push(g.PF("yt-remote-cast2-session-change",pCa)),j8.push(g.PF("yt-remote-connection-change",function(a){a?H7(h8(),"YouTube TV"):l8()||(H7(null,null),WBa())})),a=m8(),b.isAuto&&(a.id+="#dial"),g.FE("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),i8(" -- with channel params: "+
g.wg(a)),qCa(a),c.start(),h8()||rCa())},uCa=function(){var a=tCa();
E7()&&g.HG("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},tCa=function(){var a=g8().dd.$_gos();
var b=n8();b&&o8()&&(f6(a,b)||a.push(b));return tAa(a)},p8=function(){var a=vCa();
!a&&E7()&&VBa()&&(a={key:"cast-selector-receiver",name:VBa()});return a},vCa=function(){var a=tCa(),b=n8();
b||(b=l8());return g.Ia(a,function(a){return b&&b6(b,a.key)?!0:!1})},n8=function(){var a=h8();
if(!a)return null;var b=g8().ke();return g6(b,a)},pCa=function(a){i8("remote.onCastSessionChange_: "+c6(a));
if(a){var b=n8();b&&b.id==a.id?H7(b.id,"YouTube TV"):(b&&q8(),r8(a,1))}else o8()&&q8()},q8=function(){F7()?C7().stopSession():A7("stopSession called before API ready.");
var a=o8();a&&(a.disconnect(1),s8(null))},t8=function(){var a=o8();
return!!a&&3!=a.getProxyState()},i8=function(a){$6("remote",a)},g8=function(){if(!u8){var a=g.x("yt.mdx.remote.screenService_");
u8=a?new d8(a):null}return u8},h8=function(){return g.x("yt.mdx.remote.currentScreenId_")},wCa=function(a){g.ua("yt.mdx.remote.currentScreenId_",a,void 0)},xCa=function(){return g.x("yt.mdx.remote.connectData_")},k8=function(a){g.ua("yt.mdx.remote.connectData_",a,void 0)},o8=function(){return g.x("yt.mdx.remote.connection_")},s8=function(a){var b=o8();
k8(null);a||wCa("");g.ua("yt.mdx.remote.connection_",a,void 0);f8&&((0,g.C)(f8,function(b){b(a)}),f8.length=0);
b&&!a?g.TF("yt-remote-connection-change",!1):!b&&a&&g.TF("yt-remote-connection-change",!0)},l8=function(){var a=g.MG();
if(!a)return null;var b=g8().ke();return g6(b,a)},r8=function(a,b){n8()&&n8();
wCa(a.id);var c=new X7(e8,a,m8());c.connect(b,xCa());c.subscribe("beforeDisconnect",function(a){g.TF("yt-remote-before-disconnect",a)});
c.subscribe("beforeDispose",function(){o8()&&s8(null)});
s8(c)},rCa=function(){var a=l8();
a?(i8("Resume connection to: "+c6(a)),r8(a,0)):(l6(),WBa(),i8("Skipping connecting because no session screen found."))},oCa=function(){var a=m8();
if(g.Ub(a)){a=j6();var b=g.HG("yt-remote-session-name")||"",c=g.HG("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.ua("yt.mdx.remote.channelParams_",a,void 0)}},m8=function(){return g.x("yt.mdx.remote.channelParams_")||{}},qCa=function(a){a?(g.GG("yt-remote-session-app",a.app),g.GG("yt-remote-session-name",a.name)):(g.IG("yt-remote-session-app"),g.IG("yt-remote-session-name"));
g.ua("yt.mdx.remote.channelParams_",a,void 0)},v8=function(a,b,c){g.K.call(this);
this.F=a;this.l=b;this.o=new g.BF(this);g.M(this,this.o);this.o.O(b,"onCaptionsTrackListChanged",this.gQ);this.o.O(b,"captionschanged",this.MO);this.o.O(b,"captionssettingschanged",this.dD);this.o.O(b,"videoplayerreset",this.Qo);this.o.O(b,"mdxautoplaycancel",this.nH);this.V=this.o.O(b,"onVolumeChange",this.vB);this.D=!1;this.g=c;c.subscribe("proxyStateChange",this.IB,this);c.subscribe("remotePlayerChange",this.Fl,this);c.subscribe("remoteQueueChange",this.Qo,this);c.subscribe("autoplayUpNext",this.eB,
this);c.subscribe("previousNextChange",this.FB,this);c.subscribe("nowAutoplaying",this.xB,this);c.subscribe("autoplayDismissed",this.dB,this);this.suggestion=null;this.H=new g.OO(64);this.A=new g.Zt(this.ZC,500,this);g.M(this,this.A);this.B=new g.Zt(this.aD,1E3,this);g.M(this,this.B);this.K=new t6(this.nU,0,this);g.M(this,this.K);this.C={};this.L=new g.Zt(this.GD,1E3,this);g.M(this,this.L);this.I=new g.Pk(this.RM,1E3,this);g.M(this,this.I);this.N=g.y;this.dD();this.Qo();this.Fl()},w8=function(a,b){var c=
a.F,d=a.l.ea().lengthSeconds;
c.H=b||0;c.g.P("progresssync",b,d)},yCa=function(a){w8(a,0);
a.A.stop();x8(a,new g.OO(64))},z8=function(a,b){if(y8(a)&&!a.D){var c=null;
b&&(c={style:a.l.Bi()},g.bc(c,b));a.g.RC(a.l.ea(1).videoId,c);a.C=R7(a.g).l}},A8=function(a,b){var c=a.l.Vf();
if(c){var d=c.ie();var e=c.listId.toString()}var f=a.l.ea(1);c=a.g;var k=f.videoId,l=d;d=f.playerParams;f=f.Bj;var m=R7(c),n=e||m.listId;l=l||0;var q={videoId:k,currentIndex:l};N7(m,k,l);g.t(b)&&(L7(m,b),q.currentTime=b);g.t(n)&&(q.listId=n);null!=d&&(q.playerParams=d);null!=f&&(q.clickTrackingParams=f);V7(c,"setPlaylist",q);e||T7(c,m);x8(a,new g.OO(1))},zCa=function(a,b){if(b){var c=a.l.zc("captions","tracklist",{Oy:1});
c&&c.length?(a.l.Hd("captions","track",b),a.D=!1):(a.l.ql("captions"),a.D=!0)}else a.l.Hd("captions","track",{})},y8=function(a){return R7(a.g).videoId==a.l.ea(1).videoId},x8=function(a,b){a.B.stop();
var c=a.H;if(!g.VO(c,b)){var d=g.W(b,2);d!=g.W(a.H,2)&&g.dV(a.l,d);a.H=b;ACa(a.F,c,b)}},B8=function(a){g.V.call(this,{G:"div",
M:"ytp-remote",J:[{G:"div",M:"ytp-remote-display-status",J:[{G:"div",M:"ytp-remote-display-status-icon",J:[g.Rna()]},{G:"div",M:"ytp-remote-display-status-text",J:["{{statustext}}"]}]}]});this.l=new g.KV(this,250);g.M(this,this.l);this.o=a;this.O(a,"presentingplayerstatechange",this.A);BCa(this,g.aV(a))},BCa=function(a,b){if(3==a.o.Ta()){var c={RECEIVER_NAME:a.o.zc("remote","currentReceiver").name};
c=g.W(b,128)?g.U("YTP_MDX_STATUS_ERROR_2",c):b.kb()||g.W(b,4)?g.U("YTP_MDX_STATUS_PLAYING_2",c):g.U("YTP_MDX_STATUS_CONNECTED_2",c);a.updateValue("statustext",c);a.l.show()}else a.l.hide()},C8=function(a,b){g.JZ.call(this,g.U("YTP_MDX_TITLE"),0,a,b);
this.l=a;this.F={};this.O(a,"onMdxReceiversChange",this.I);this.O(a,"presentingplayerstatechange",this.I);this.I()},D8=function(a){g.zV.call(this,a);
g.OG({YTP_MDX_CAST_SELECTOR:"Transmitir...",YTP_MDX_MY_COMPUTER:"Este computador",YTP_MDX_PLAYER_ERROR:"Este v\u00eddeo n\u00e3o se encontra dispon\u00edvel para reprodu\u00e7\u00e3o remota.",YTP_MDX_STATUS_CONNECTED_2:"Liga\u00e7\u00e3o a $RECEIVER_NAME estabelecida",YTP_MDX_STATUS_ERROR_2:"Erro em $RECEIVER_NAME",YTP_MDX_STATUS_PLAYING_2:"A reproduzir em $RECEIVER_NAME",YTP_MDX_TITLE:"Reproduzir em"});this.o={key:e6(),name:g.U("YTP_MDX_MY_COMPUTER")};this.B=null;this.C=[];this.I=this.l=null;this.F=
[this.o];this.A=this.o;this.D=new g.OO(64);this.H=0;if(!g.vM(g.X(this.g))){a=this.g;var b=g.dI(a);b&&(b=b.xo())&&(b=new C8(a,b),g.M(this,b));b=new B8(a);g.M(this,b);g.tV(a,b.element,4)}},ACa=function(a,b,c){a.D=c;
a.g.P("presentingplayerstatechange",new g.aP(c,b))},E8=function(a,b){if(b.key!=a.A.key)if(b.key==a.o.key)q8();
else{a.A=b;var c=a.g.getPlaylistId();var d=a.g.ea(1),e=d.videoId;if(c||e){var f=a.g.Vf();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.jc(l).videoId}else k=[e];f=a.g.getCurrentTime(1);c={videoIds:k,listId:c,videoId:e,playerParams:d.playerParams,clickTrackingParams:d.Bj,index:Math.max(a.g.Mz(),0),currentTime:0==f?void 0:f}}else c=null;i8("Connecting to: "+g.wg(b));"cast-selector-receiver"==b.key?(k8(c||null),F7()?C7().setLaunchParams(c||null):A7("setLaunchParams called before ready.")):!c&&
t8()&&h8()==b.key?g.TF("yt-remote-connection-change",!0):(q8(),k8(c||null),c=g8().ke(),(c=g6(c,b.key))&&r8(c,1))}},QAa={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"<"},D6={"'":"\\'"},CCa={},pAa={bW:"atp",w0:"ska",L_:"que",WZ:"mus",s0:"sus"};
$5.prototype.ln=function(){var a=new $5({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.o=this.o;a.l=this.l;a.g=this.g};
var m6,i6="",q6=n6("loadGamesSDK")?"/cast_game_sender.js":"/cast_sender.js",IAa=n6("loadCastFramework")||n6("loadCastApplicationFramework"),SBa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];g.A(t6,g.K);g.h=t6.prototype;g.h.bI=function(a){this.A=arguments;this.g=!1;this.xa?this.o=(0,g.G)()+this.uc:this.xa=g.qg(this.B,this.uc)};
g.h.stop=function(){this.xa&&(g.rg(this.xa),this.xa=null);this.o=null;this.g=!1;this.A=[]};
g.h.pause=function(){++this.l};
g.h.resume=function(){this.l&&(--this.l,!this.l&&this.g&&(this.g=!1,this.C.apply(null,this.A)))};
g.h.U=function(){this.stop();t6.Z.U.call(this)};
g.h.cI=function(){this.o?(this.xa=g.qg(this.B,this.o-(0,g.G)()),this.o=null):(this.xa=null,this.l?this.g=!0:(this.g=!1,this.C.apply(null,this.A)))};u6.prototype.stringify=function(a){return g.w.JSON.stringify(a,void 0)};
u6.prototype.parse=function(a){return g.w.JSON.parse(a,void 0)};g.h=v6.prototype;g.h.ji=null;g.h.xf=!1;g.h.pk=null;g.h.fv=null;g.h.Uj=null;g.h.rj=null;g.h.mh=null;g.h.Eh=null;g.h.Ii=null;g.h.Pc=null;g.h.Ul=0;g.h.yf=null;g.h.Ip=null;g.h.nh=null;g.h.Rk=-1;g.h.zC=!0;g.h.Sh=!1;g.h.xr=0;g.h.Zo=null;var OAa={},y6={};g.h=v6.prototype;g.h.setTimeout=function(a){this.B=a};
g.h.gT=function(a){a=a.target;var b=this.Zo;b&&3==g.mx(a)?b.pj():this.OD(a)};
g.h.OD=function(a){try{if(a==this.Pc)a:{var b=g.mx(this.Pc),c=this.Pc.l,d=this.Pc.getStatus();if(g.rd&&!g.nc(10)||g.td&&!g.mc("420+")){if(4>b)break a}else if(3>b||3==b&&!g.$e&&!g.qx(this.Pc))break a;this.Sh||4!=b||7==c||(8==c||0>=d?this.g.tf(3):this.g.tf(2));F6(this);var e=this.Pc.getStatus();this.Rk=e;var f=g.qx(this.Pc);(this.xf=200==e)?(4==b&&B6(this),this.C?(PAa(this,b,f),g.$e&&this.xf&&3==b&&(this.A.R(this.l,"tick",this.ZS),this.l.start())):A6(this,f),this.xf&&!this.Sh&&(4==b?this.g.No(this):
(this.xf=!1,x6(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.nh=3,z6(13)):(this.nh=0,z6(14)),B6(this),C6(this))}}catch(k){this.Pc&&g.qx(this.Pc)}finally{}};
g.h.ZS=function(){var a=g.mx(this.Pc),b=g.qx(this.Pc);this.Ul<b.length&&(F6(this),PAa(this,a,b),this.xf&&4!=a&&x6(this))};
g.h.kS=function(a){E6((0,g.z)(this.jS,this,a),0)};
g.h.jS=function(a){this.Sh||(F6(this),A6(this,a),x6(this))};
g.h.QB=function(a){E6((0,g.z)(this.iS,this,a),0)};
g.h.iS=function(a){this.Sh||(B6(this),this.xf=a,this.g.No(this),this.g.tf(4))};
g.h.cancel=function(){this.Sh=!0;B6(this)};
g.h.BS=function(){this.pk=null;var a=(0,g.G)();0<=a-this.fv?(2!=this.rj&&this.g.tf(3),B6(this),this.nh=2,z6(18),C6(this)):SAa(this,this.fv-a)};g.h=VAa.prototype;g.h.ur=null;g.h.se=null;g.h.bp=!1;g.h.ay=null;g.h.An=null;g.h.vr=null;g.h.wr=null;g.h.Le=null;g.h.yg=-1;g.h.Qk=null;g.h.tk=null;g.h.connect=function(a){this.wr=a;a=H6(this.g,null,this.wr);z6(3);this.ay=(0,g.G)();var b=this.g.F;null!=b?(this.Qk=b[0],(this.tk=b[1])?(this.Le=1,WAa(this)):(this.Le=2,J6(this))):(Z5(a,"MODE","init"),this.se=new v6(this,void 0,void 0,void 0),this.se.ji=this.ur,w6(this.se,a,!1,null,!0),this.Le=0)};
g.h.oH=function(a){if(a)this.Le=2,J6(this);else{z6(4);var b=this.g;b.hf=b.dh.yg;Q6(b,9)}a&&this.tf(2)};
g.h.Qq=function(a){return this.g.Qq(a)};
g.h.abort=function(){this.se&&(this.se.cancel(),this.se=null);this.yg=-1};
g.h.Zx=function(){return!1};
g.h.JB=function(a,b){this.yg=a.Rk;if(0==this.Le)if(b){try{var c=this.l.parse(b)}catch(d){c=this.g;c.hf=this.yg;Q6(c,2);return}this.Qk=c[0];this.tk=c[1]}else c=this.g,c.hf=this.yg,Q6(c,2);else if(2==this.Le)if(this.bp)z6(7),this.vr=(0,g.G)();else if("11111"==b){if(z6(6),this.bp=!0,this.An=(0,g.G)(),c=this.An-this.ay,!g.rd||g.nc(10)||500>c)this.yg=200,this.se.cancel(),z6(12),I6(this.g,this,!0)}else z6(8),this.An=this.vr=(0,g.G)(),this.bp=!1};
g.h.No=function(){this.yg=this.se.Rk;if(this.se.xf)0==this.Le?this.tk?(this.Le=1,WAa(this)):(this.Le=2,J6(this)):2==this.Le&&((!g.rd||g.nc(10)?!this.bp:200>this.vr-this.An)?(z6(11),I6(this.g,this,!1)):(z6(12),I6(this.g,this,!0)));else{0==this.Le?z6(9):2==this.Le&&z6(10);var a=this.g;a.hf=this.yg;Q6(a,2)}};
g.h.Nl=function(){return this.g.Nl()};
g.h.isActive=function(){return this.g.isActive()};
g.h.tf=function(a){this.g.tf(a)};g.h=K6.prototype;g.h.Dk=null;g.h.Qd=null;g.h.tc=null;g.h.tr=null;g.h.Dn=null;g.h.rw=null;g.h.Sn=null;g.h.zl=0;g.h.fO=0;g.h.qd=null;g.h.fh=null;g.h.qg=null;g.h.Wh=null;g.h.dh=null;g.h.Hp=null;g.h.Ej=-1;g.h.Zy=-1;g.h.hf=-1;g.h.jj=0;g.h.Yi=0;g.h.Uh=8;var R6=new g.Bf;g.A(YAa,g.Ye);g.A(ZAa,g.Ye);g.A($Aa,g.Ye);g.h=K6.prototype;g.h.connect=function(a,b,c,d,e){z6(0);this.tr=b;this.Dk=c||{};d&&g.t(e)&&(this.Dk.OSID=d,this.Dk.OAID=e);this.C?(E6((0,g.z)(this.Pw,this,a),100),dBa(this)):this.Pw(a)};
g.h.Pw=function(a){this.dh=new VAa(this);this.dh.ur=null;this.dh.l=this.B;this.dh.connect(a)};
g.h.Zx=function(){return 0==this.g};
g.h.OB=function(a){this.fh=null;gBa(this,a)};
g.h.NB=function(){this.qg=null;this.tc=new v6(this,this.o,"rpc",this.D);this.tc.ji=null;this.tc.xr=0;var a=this.rw.clone();g.Fm(a,"RID","rpc");g.Fm(a,"SID",this.o);g.Fm(a,"CI",this.Hp?"0":"1");g.Fm(a,"AID",this.Ej);L6(this,a);if(!g.rd||g.nc(10))g.Fm(a,"TYPE","xmlhttp"),w6(this.tc,a,!0,this.Sn,!1);else{g.Fm(a,"TYPE","html");var b=this.tc,c=!!this.Sn;b.rj=3;b.mh=Y5(a.clone());RAa(b,c)}};
g.h.JB=function(a,b){if(0!=this.g&&(this.tc==a||this.Qd==a))if(this.hf=a.Rk,this.Qd==a&&3==this.g)if(7<this.Uh){try{var c=this.B.parse(b)}catch(f){c=null}if(g.xa(c)&&3==c.length)if(0==c[0])a:{if(!this.qg){if(this.tc)if(this.tc.Uj+3E3<this.Qd.Uj)N6(this),this.tc.cancel(),this.tc=null;else break a;P6(this);z6(19)}}else this.Zy=c[1],0<this.Zy-this.Ej&&37500>c[2]&&this.Hp&&0==this.Yi&&!this.Wh&&(this.Wh=E6((0,g.z)(this.HO,this),6E3));else Q6(this,11)}else b!=CCa.fX.g&&Q6(this,11);else if(this.tc==a&&
N6(this),!g.D(b)){c=this.B.parse(b);g.xa(c);for(var d=0;d<c.length;d++){var e=c[d];this.Ej=e[0];e=e[1];2==this.g?"c"==e[0]?(this.o=e[1],this.Sn=e[2],e=e[3],null!=e?this.Uh=e:this.Uh=6,this.g=3,this.qd&&this.qd.Ew(),this.rw=H6(this,this.Nl()?this.Sn:null,this.tr),hBa(this)):"stop"==e[0]&&Q6(this,7):3==this.g&&("stop"==e[0]?Q6(this,7):"noop"!=e[0]&&this.qd&&this.qd.Dw(e),this.Yi=0)}}};
g.h.HO=function(){null!=this.Wh&&(this.Wh=null,this.tc.cancel(),this.tc=null,P6(this),z6(20))};
g.h.No=function(a){if(this.tc==a){N6(this);this.tc=null;var b=2}else if(this.Qd==a)this.Qd=null,b=1;else return;this.hf=a.Rk;if(0!=this.g)if(a.xf)1==b?(b=(0,g.G)()-a.Uj,R6.dispatchEvent(new ZAa(R6,a.Ii?a.Ii.length:0,b,this.jj)),M6(this),this.A.length=0):hBa(this);else{var c=a.nh,d;if(!(d=3==c||7==c||0==c&&0<this.hf)){if(d=1==b)this.Qd||this.fh||1==this.g||2<=this.jj?d=!1:(this.fh=E6((0,g.z)(this.OB,this,a),iBa(this,this.jj)),this.jj++,d=!0);d=!(d||2==b&&P6(this))}if(d)switch(c){case 1:Q6(this,5);
break;case 4:Q6(this,10);break;case 3:Q6(this,6);break;case 7:Q6(this,12);break;default:Q6(this,2)}}};
g.h.JH=function(a){if(!g.Ma(arguments,this.g))throw Error("Unexpected channel state: "+this.g);};
g.h.bU=function(a){a?z6(2):(z6(1),jBa(this,8))};
g.h.Qq=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new g.cx;a.F=!1;return a};
g.h.isActive=function(){return!!this.qd&&this.qd.isActive(this)};
g.h.tf=function(a){R6.dispatchEvent(new $Aa(R6,a))};
g.h.Nl=function(){return!(!g.rd||g.nc(10))};
g.h=kBa.prototype;g.h.Ew=function(){};
g.h.Dw=function(){};
g.h.Cw=function(){};
g.h.Fq=function(){};
g.h.Hx=function(){return{}};
g.h.isActive=function(){return!0};g.A(T6,g.K);T6.prototype.o=function(){500<this.uc&&24E4>2*this.uc&&(this.uc*=2);this.A();this.l&&this.start()};
T6.prototype.start=function(){g.$t(this.g,this.uc);this.l=(0,g.G)()+this.uc};
T6.prototype.stop=function(){this.g.stop();this.l=0};
T6.prototype.isActive=function(){return this.g.isActive()};g.A(U6,kBa);g.h=U6.prototype;g.h.subscribe=function(a,b,c){return this.o.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.o.unsubscribe(a,b,c)};
g.h.Jd=function(a){return this.o.Jd(a)};
g.h.P=function(a,b){return this.o.P.apply(this.o,arguments)};
g.h.dispose=function(){this.I||(this.I=!0,g.We(this.o),nBa(this),g.We(this.l),this.l=null)};
g.h.ha=function(){return this.I};
g.h.connect=function(a,b,c){if(!this.g||2!=this.g.g){this.H="";this.l.stop();this.B=a||null;this.A=b||0;a=this.K+"/test";b=this.K+"/bind";var d=new K6(c?c.firstTestResults:null,c?c.secondTestResults:null,this.L),e=this.g;e&&(e.qd=null);d.qd=this;this.g=d;e?this.g.connect(a,b,this.C,e.o,e.Ej):c?this.g.connect(a,b,this.C,c.sessionId,c.arrayId):this.g.connect(a,b,this.C)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.bc(c,b);this.l.isActive()||2==(this.g?this.g.g:0)?this.D.push(c):V6(this)&&eBa(this.g,c)};
g.h.Ew=function(){S6(this.l);this.B=null;this.A=0;if(this.D.length){var a=this.D;this.D=[];for(var b=0,c=a.length;b<c;++b)eBa(this.g,a[b])}this.P("handlerOpened")};
g.h.Cw=function(a){var b=2==a&&401==this.g.hf;if(4!=a&&!b){if(6==a||410==this.g.hf)b=this.l,b.g.stop(),b.uc=500;this.l.start()}this.P("handlerError",a)};
g.h.Fq=function(a){if(!this.l.isActive())this.P("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.D.push(d)}};
g.h.Hx=function(){var a={v:2};this.H&&(a.gsessionid=this.H);0!=this.A&&(a.ui=""+this.A);0!=this.F&&(a.ui=""+this.F);this.B&&g.bc(a,this.B);return a};
g.h.Dw=function(a){"S"==a[0]?this.H=a[1]:"gracefulReconnect"==a[0]?(S6(this.l),this.l.start(),cBa(this.g)):this.P("handlerMessage",new lBa(a[0],a[1]))};
g.h.GU=function(){this.l.isActive();var a=this.g,b=0;a.tc&&b++;a.Qd&&b++;0!=b?this.l.start():this.connect(this.B,this.A)};W6.prototype.A=function(a,b,c,d){b?a(d):a({text:c.responseText})};
W6.prototype.o=function(a,b){a(Error("Request error: "+b.status))};
W6.prototype.B=function(a){a(Error("request timed out"))};var vBa=(0,g.G)(),Z6=null,b7=Array(50),a7=-1,c7=!1;g.A(d7,g.EF);d7.prototype.ke=function(){return this.g};
d7.prototype.contains=function(a){return!!f6(this.g,a)};
d7.prototype.get=function(a){return a?g6(this.g,a):null};
d7.prototype.info=function(a){$6(this.D,a)};g.A(e7,g.EF);var DCa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.h=e7.prototype;g.h.start=function(){!this.g&&(0,window.isNaN)(this.xa)&&this.TD()};
g.h.stop=function(){this.g&&(this.g.abort(),this.g=null);(0,window.isNaN)(this.xa)||(g.PD(this.xa),this.xa=window.NaN)};
g.h.U=function(){this.stop();e7.Z.U.call(this)};
g.h.TD=function(){this.xa=window.NaN;this.g=g.kE(X6(this.C,"/pairing/get_screen"),{method:"POST",Lb:{pairing_code:this.B},timeout:5E3,Hb:(0,g.z)(this.IU,this),onError:(0,g.z)(this.HU,this),ud:(0,g.z)(this.JU,this)})};
g.h.IU=function(a,b){this.g=null;var c=b.screen||{};c.dialId=this.o;c.name=this.A;this.P("pairingComplete",new a6(c))};
g.h.HU=function(a){this.g=null;a.status&&404==a.status?this.l>=DCa.length?this.P("pairingFailed",Error("DIAL polling timed out")):(a=DCa[this.l],this.xa=g.ND((0,g.z)(this.TD,this),a),this.l++):this.P("pairingFailed",Error("Server error "+a.status))};
g.h.JU=function(){this.g=null;this.P("pairingFailed",Error("Server not responding"))};g.A(g7,d7);g.h=g7.prototype;g.h.start=function(){f7(this)&&this.P("screenChange");!g.HG("yt-remote-lounge-token-expiration")&&zBa(this);g.PD(this.l);this.l=g.ND((0,g.z)(this.start,this),1E4)};
g.h.add=function(a,b){f7(this);wBa(this,a);h7(this,!1);this.P("screenChange");b(a);a.token||zBa(this)};
g.h.remove=function(a,b){var c=f7(this);yBa(this,a)&&(h7(this,!1),c=!0);b(a);c&&this.P("screenChange")};
g.h.Dp=function(a,b,c,d){var e=f7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,h7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.P("screenChange")};
g.h.U=function(){g.PD(this.l);g7.Z.U.call(this)};
g.h.oI=function(a){f7(this);var b=this.g.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}h7(this,!b);b&&$6(this.D,"Missed "+b+" lounge tokens.")};
g.h.nI=function(a){$6(this.D,"Requesting lounge tokens failed: "+a)};g.A(j7,g.EF);g.h=j7.prototype;g.h.start=function(){var a=(0,window.parseInt)(g.HG("yt-remote-fast-check-period")||"0",10);(this.A=(0,g.G)()-144E5<a?0:a)?l7(this):(this.A=(0,g.G)()+3E5,g.GG("yt-remote-fast-check-period",this.A),this.ru())};
g.h.isEmpty=function(){return g.Ub(this.g)};
g.h.update=function(){i7("Updating availability on schedule.");var a=this.C(),b=g.Jb(this.g,function(b,d){return b&&!!g6(a,d)},this);
k7(this,b)};
g.h.U=function(){g.PD(this.o);this.o=window.NaN;this.l&&(this.l.abort(),this.l=null);j7.Z.U.call(this)};
g.h.ru=function(){g.PD(this.o);this.o=window.NaN;this.l&&this.l.abort();var a=CBa(this);if(g.Mb(a)){var b=X6(this.B,"/pairing/get_screen_availability");this.l=Y6(this.B,b,{lounge_token:g.Ob(a).join(",")},(0,g.z)(this.LR,this,a),(0,g.z)(this.KR,this))}else k7(this,{}),l7(this)};
g.h.LR=function(a,b){this.l=null;var c=g.Ob(CBa(this));if(g.fb(c,g.Ob(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;k7(this,d);l7(this)}else this.fc("Changing Screen set during request."),this.ru()};
g.h.KR=function(a){this.fc("Screen availability failed: "+a);this.l=null;l7(this)};
g.h.fc=function(a){$6("OnlineScreenService",a)};g.A(m7,d7);g.h=m7.prototype;g.h.start=function(){this.o.start();this.l.start();this.g.length&&(this.P("screenChange"),this.l.isEmpty()||this.P("onlineScreenChange"))};
g.h.add=function(a,b,c){this.o.add(a,b,c)};
g.h.remove=function(a,b,c){this.o.remove(a,b,c);this.l.update()};
g.h.Dp=function(a,b,c,d){this.o.contains(a)?this.o.Dp(a,b,c,d):(a="Updating name of unknown screen: "+a.name,$6(this.D,a),d(Error(a)))};
g.h.ke=function(a){return a?this.g:g.Ua(this.g,(0,g.Fd)(this.A,function(a){return!this.contains(a)},this))};
g.h.UD=function(){return(0,g.Fd)(this.ke(!0),function(a){return!!this.l.g[a.id]},this)};
g.h.VD=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new e7(this.C,a,b,c);f.subscribe("pairingComplete",(0,g.z)(function(a){g.We(f);d(n7(this,a))},this));
f.subscribe("pairingFailed",function(a){g.We(f);e(a)});
f.start();return(0,g.z)(f.stop,f)};
g.h.LU=function(a,b,c,d){g.kE(X6(this.C,"/pairing/get_screen"),{method:"POST",Lb:{pairing_code:a},timeout:5E3,Hb:(0,g.z)(function(a,d){var e=new a6(d.screen||{});if(!e.name||GBa(this,e.name)){a:{var f=e.name;for(var m=2,n=b(f,m);GBa(this,n);){m++;if(20<m)break a;n=b(f,m)}f=n}e.name=f}c(n7(this,e))},this),
onError:(0,g.z)(function(a){d(Error("pairing request failed: "+a.status))},this),
ud:(0,g.z)(function(){d(Error("pairing request timed out."))},this)})};
g.h.U=function(){g.We(this.o);g.We(this.l);m7.Z.U.call(this)};
g.h.EI=function(){HBa(this);this.P("screenChange");this.l.update()};
m7.prototype.dispose=m7.prototype.dispose;g.A(p7,g.EF);g.h=p7.prototype;g.h.Oo=function(a){this.o=a;this.P("sessionScreen",this.o)};
g.h.qe=function(a){this.ha()||(a&&q7(this,""+a),this.o=null,this.P("sessionScreen",null))};
g.h.info=function(a){$6(this.L,a)};
g.h.XD=function(){return null};
g.h.Au=function(a){var b=this.l;a?(b.displayStatus=new window.chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;window.chrome.cast.setReceiverDisplayStatus(b,(0,g.z)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.z)(function(){q7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.U=function(){this.Au("");p7.Z.U.call(this)};g.A(r7,p7);g.h=r7.prototype;g.h.zu=function(a){if(this.g){if(this.g==a)return;q7(this,"Overriding cast sesison with new session object");this.g.removeUpdateListener(this.C);this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B)}this.g=a;this.g.addUpdateListener(this.C);this.g.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.B);JBa(this)};
g.h.Fj=function(a){this.info("launchWithParams no-op for Cast: "+g.wg(a))};
g.h.stop=function(){this.g?this.g.stop((0,g.z)(function(){this.qe()},this),(0,g.z)(function(){this.qe(Error("Failed to stop receiver app."))},this)):this.qe(Error("Stopping cast device witout session."))};
g.h.Au=g.y;g.h.U=function(){this.info("disposeInternal");g.PD(this.A);this.A=0;this.g&&(this.g.removeUpdateListener(this.C),this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B));this.g=null;r7.Z.U.call(this)};
g.h.LS=function(a,b){if(!this.ha())if(b){var c=g.Xw(b);if(g.Aa(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.wg(c));switch(d){case "mdxSessionStatus":IBa(this,c.screenId);break;default:q7(this,"Unknown youtube message: "+d)}}else q7(this,"Unable to parse message.")}else q7(this,"No data in message.")};
g.h.Sx=function(a,b,c,d){FBa(this.H,this.l.label,a,this.l.friendlyName,(0,g.z)(function(e){e?b(e):0<=d?(q7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.ND((0,g.z)(this.Sx,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.XD=function(){return this.g};
g.h.MU=function(a){this.ha()||a||(q7(this,"Cast session died."),this.qe())};g.A(s7,p7);g.h=s7.prototype;g.h.zu=function(a){this.A=a;this.A.addUpdateListener(this.K)};
g.h.Fj=function(a){this.B=a;this.D()};
g.h.stop=function(){this.g();this.g=g.y;g.PD(this.C);this.A?this.A.stop((0,g.z)(this.qe,this,null),(0,g.z)(this.qe,this,"Failed to stop DIAL device.")):this.qe()};
g.h.U=function(){this.g();this.g=g.y;g.PD(this.C);this.A&&this.A.removeUpdateListener(this.K);this.A=null;s7.Z.U.call(this)};
g.h.PU=function(a){this.ha()||a||(q7(this,"DIAL session died."),this.g(),this.g=g.y,this.qe())};
g.h.ks=function(a){this.I=e6();if(this.B){var b=new window.chrome.cast.DialLaunchResponse(!0,LBa(this));a(b);KBa(this)}else this.D=(0,g.z)(function(){g.PD(this.C);this.D=g.y;this.C=window.NaN;var b=new window.chrome.cast.DialLaunchResponse(!0,LBa(this));a(b);KBa(this)},this),this.C=g.ND((0,g.z)(function(){this.D()},this),100)};
g.h.VJ=function(a,b,c){FBa(this.H,this.F.receiver.label,a,this.l.friendlyName,(0,g.z)(function(a){a&&a.token?(this.Oo(a),b(new window.chrome.cast.DialLaunchResponse(!1))):this.ks(b,c)},this),(0,g.z)(function(a){q7(this,"Failed to get DIAL screen: "+a);
this.ks(b,c)},this))};g.A(t7,p7);t7.prototype.stop=function(){this.qe()};
t7.prototype.zu=g.y;t7.prototype.Fj=function(){g.PD(this.g);this.g=window.NaN;var a=g6(this.H.ke(),this.l.label);a?this.Oo(a):this.qe(Error("No such screen"))};
t7.prototype.U=function(){g.PD(this.g);this.g=window.NaN;t7.Z.U.call(this)};g.A(u7,g.EF);g.h=u7.prototype;
g.h.init=function(a,b){window.chrome.cast.timeout.requestSession=3E4;var c=new window.chrome.cast.SessionRequest(this.D);this.F||(c.dialRequest=new window.chrome.cast.DialRequest("YouTube"));var d=window.chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?window.chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:window.chrome.cast.DefaultActionPolicy.CREATE_SESSION;c=new window.chrome.cast.ApiConfig(c,(0,g.z)(this.KB,this),(0,g.z)(this.vR,this),d,e);c.customDialLaunchCallback=(0,g.z)(this.sP,this);window.chrome.cast.initialize(c,
(0,g.z)(function(){this.ha()||(window.chrome.cast.addReceiverActionListener(this.A),sBa(),this.l.subscribe("onlineScreenChange",(0,g.z)(this.WD,this)),this.o=NBa(this),window.chrome.cast.setCustomReceivers(this.o,g.y,(0,g.z)(function(a){this.fc("Failed to set initial custom receivers: "+g.wg(a))},this)),this.P("yt-remote-cast2-availability-change",w7(this)),b(!0))},this),(0,g.z)(function(a){this.fc("Failed to initialize API: "+g.wg(a));
b(!1)},this))};
g.h.IT=function(a,b){v7("Setting connected screen ID: "+a+" -> "+b);if(this.g){var c=this.g.o;if(!a||c&&c.id!=a)v7("Unsetting old screen status: "+this.g.l.friendlyName),x7(this,null)}if(a&&b){if(!this.g){c=g6(this.l.ke(),a);if(!c){v7("setConnectedScreenStatus: Unknown screen.");return}var d=MBa(this,c);d||(v7("setConnectedScreenStatus: Connected receiver not custom..."),d=new window.chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM,this.o.push(d),
window.chrome.cast.setCustomReceivers(this.o,g.y,(0,g.z)(function(a){this.fc("Failed to set initial custom receivers: "+g.wg(a))},this)));
v7("setConnectedScreenStatus: new active receiver: "+d.friendlyName);x7(this,new t7(this.l,d),!0)}this.g.Au(b)}else v7("setConnectedScreenStatus: no screen.")};
g.h.JT=function(a){this.ha()?this.fc("Setting connection data on disposed cast v2"):this.g?this.g.Fj(a):this.fc("Setting connection data without a session")};
g.h.OU=function(){this.ha()?this.fc("Stopping session on disposed cast v2"):this.g?(this.g.stop(),x7(this,null)):v7("Stopping non-existing session")};
g.h.requestSession=function(){window.chrome.cast.requestSession((0,g.z)(this.KB,this),(0,g.z)(this.PR,this))};
g.h.U=function(){this.l.unsubscribe("onlineScreenChange",(0,g.z)(this.WD,this));window.chrome&&window.chrome.cast&&window.chrome.cast.removeReceiverActionListener(this.A);g.Ra(g.x("yt.mdx.remote.debug.handlers_")||[],pBa);g.We(this.g);u7.Z.U.call(this)};
g.h.fc=function(a){$6("Controller",a)};
g.h.LB=function(a,b){this.g==a&&(b||x7(this,null),this.P("yt-remote-cast2-session-change",b))};
g.h.rR=function(a,b){if(!this.ha())if(a)switch(a.friendlyName=window.chrome.cast.unescape(a.friendlyName),v7("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case window.chrome.cast.ReceiverAction.CAST:if(this.g)if(this.g.l.label!=a.label)v7("onReceiverAction_: Stopping active receiver: "+this.g.l.friendlyName),this.g.stop();else{v7("onReceiverAction_: Casting to active receiver.");this.g.o&&this.P("yt-remote-cast2-session-change",this.g.o);break}switch(a.receiverType){case window.chrome.cast.ReceiverType.CUSTOM:x7(this,
new t7(this.l,a));break;case window.chrome.cast.ReceiverType.DIAL:x7(this,new s7(this.l,a,this.C));break;case window.chrome.cast.ReceiverType.CAST:x7(this,new r7(this.l,a));break;default:this.fc("Unknown receiver type: "+a.receiverType)}break;case window.chrome.cast.ReceiverAction.STOP:this.g&&this.g.l.label==a.label?this.g.stop():this.fc("Stopping receiver w/o session: "+a.friendlyName)}else this.fc("onReceiverAction_ called without receiver.")};
g.h.sP=function(a){if(this.ha())return window.Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=window.chrome.cast.ReceiverType.DIAL&&(this.fc("Not DIAL receiver: "+b.friendlyName),b.receiverType=window.chrome.cast.ReceiverType.DIAL);var c=this.g?this.g.l:null;if(!c||c.label!=b.label)return this.fc("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),window.Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=window.chrome.cast.ReceiverType.DIAL){if(this.g.o)return v7("Reselecting dial screen."),
this.P("yt-remote-cast2-session-change",this.g.o),window.Promise.resolve(new window.chrome.cast.DialLaunchResponse(!1));this.fc('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);x7(this,new s7(this.l,b,this.C))}b=this.g;b.F=a;return b.F.appState==window.chrome.cast.DialAppState.RUNNING?new window.Promise((0,g.z)(b.VJ,b,(b.F.extraData||{}).screenId||null)):new window.Promise((0,g.z)(b.ks,b))};
g.h.KB=function(a){if(!this.ha()){v7("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=window.chrome.cast.ReceiverType.CUSTOM){if(!this.g)if(b.receiverType==window.chrome.cast.ReceiverType.CAST)v7("Got resumed cast session before resumed mdx connection."),b.friendlyName=window.chrome.cast.unescape(b.friendlyName),x7(this,new r7(this.l,b),!0);else{this.fc("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.g.l,d=g6(this.l.ke(),c.label);
d&&b6(d,b.label)&&c.receiverType!=window.chrome.cast.ReceiverType.CAST&&b.receiverType==window.chrome.cast.ReceiverType.CAST&&(v7("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.We(this.g),this.g=new r7(this.l,b),this.g.subscribe("sessionScreen",(0,g.z)(this.LB,this,this.g)),this.g.Fj(null));this.g.zu(a)}}};
g.h.NU=function(){return this.g?this.g.XD():null};
g.h.PR=function(a){this.ha()||(this.fc("Failed to estabilish a session: "+g.wg(a)),a.code!=window.chrome.cast.ErrorCode.CANCEL&&x7(this,null))};
g.h.vR=function(a){v7("Receiver availability updated: "+a);if(!this.ha()){var b=w7(this);this.B=a==window.chrome.cast.ReceiverAvailability.AVAILABLE;w7(this)!=b&&this.P("yt-remote-cast2-availability-change",w7(this))}};
g.h.WD=function(){this.ha()||(this.o=NBa(this),v7("Updating custom receivers: "+g.wg(this.o)),window.chrome.cast.setCustomReceivers(this.o,g.y,(0,g.z)(function(){this.fc("Failed to set custom receivers.")},this)),this.P("yt-remote-cast2-availability-change",w7(this)))};
u7.prototype.setLaunchParams=u7.prototype.JT;u7.prototype.setConnectedScreenStatus=u7.prototype.IT;u7.prototype.stopSession=u7.prototype.OU;u7.prototype.getCastSession=u7.prototype.NU;u7.prototype.requestSession=u7.prototype.requestSession;u7.prototype.init=u7.prototype.init;u7.prototype.dispose=u7.prototype.dispose;var D7=[];g.h=I7.prototype;
g.h.reset=function(a){this.listId="";this.index=-1;this.videoId="";J7(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.g=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.l=a.trackData,this.Lf=a.hasPrevious,this.hasNext=a.hasNext,this.F=a.playerTime,this.D=a.playerTimeAt,this.B=a.seekableStart,this.o=a.seekableEnd,this.H=a.duration,this.I=a.loadedTime,this.A=a.liveIngestionTime,this.C=!(0,window.isNaN)(this.A))};
g.h.kb=function(){return 1==this.g};
g.h.isAdPlaying=function(){return 1081==this.g};
g.h.getDuration=function(){return this.C?this.H+K7(this):this.H};
g.h.clone=function(){return new I7(O7(this))};g.A(Q7,g.EF);g.h=Q7.prototype;g.h.play=function(){1==this.g?(this.l?this.l.play(null,g.y,W7(this,"play")):V7(this,"play"),U7(this,1,M7(R7(this))),this.P("remotePlayerChange")):S7(this,this.play)};
g.h.pause=function(){1==this.g?(this.l?this.l.pause(null,g.y,W7(this,"pause")):V7(this,"pause"),U7(this,2,M7(R7(this))),this.P("remotePlayerChange")):S7(this,this.pause)};
g.h.SD=function(a){if(1==this.g){if(this.l){var b=R7(this),c=new window.chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=b.kb()||3==b.g?window.chrome.cast.media.ResumeState.PLAYBACK_START:window.chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.l.seek(c,g.y,W7(this,"seekTo",{newTime:a}))}else V7(this,"seekTo",{newTime:a});U7(this,3,a);this.P("remotePlayerChange")}else S7(this,g.Da(this.SD,a))};
g.h.stop=function(){if(1==this.g){this.l?this.l.stop(null,g.y,W7(this,"stopVideo")):V7(this,"stopVideo");var a=R7(this);a.index=-1;a.videoId="";J7(a);T7(this,a);this.P("remotePlayerChange")}else S7(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.g){var c=R7(this);if(this.o){if(c.volume!=a){var d=Math.round(a)/100;this.o.setReceiverVolumeLevel(d,(0,g.z)(function(){$6("CP","set receiver volume: "+d)},this),(0,g.z)(function(){this.fc("failed to set receiver volume.")},this))}c.muted!=b&&this.o.setReceiverMuted(b,(0,g.z)(function(){$6("CP","set receiver muted: "+b)},this),(0,g.z)(function(){this.fc("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);V7(this,"setVolume",e)}c.muted=b;c.volume=a;T7(this,c)}else S7(this,g.Da(this.setVolume,a,b))};
g.h.RC=function(a,b){if(1==this.g){var c=R7(this),d={videoId:a};b&&(c.l={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,format:b.format,kind:b.kind},d.style=g.wg(b.style),g.bc(d,c.l));V7(this,"setSubtitlesTrack",d);T7(this,c)}else S7(this,g.Da(this.RC,a,b))};
g.h.lv=function(a,b){if(1==this.g){V7(this,"setAudioTrack",{videoId:a,audioTrackId:b.Nb.id});var c=R7(this);c.audioTrackId=b.Nb.id;T7(this,c)}else S7(this,g.Da(this.lv,a,b))};
g.h.RD=function(a,b){if(1==this.g){if(a&&b){var c=R7(this);N7(c,a,b);T7(this,c)}V7(this,"previous")}else S7(this,g.Da(this.RD,a,b))};
g.h.QD=function(a,b){if(1==this.g){if(a&&b){var c=R7(this);N7(c,a,b);T7(this,c)}V7(this,"next")}else S7(this,g.Da(this.QD,a,b))};
g.h.jx=function(){1==this.g?V7(this,"dismissAutoplay"):S7(this,this.jx)};
g.h.dispose=function(){if(3!=this.g){var a=this.g;this.g=3;this.P("proxyStateChange",a,this.g)}Q7.Z.dispose.call(this)};
g.h.U=function(){$Ba(this);this.A=null;this.B.clear();P7(this,null);Q7.Z.U.call(this)};
g.h.ov=function(a){if((a!=this.g||2==a)&&3!=this.g&&0!=a){var b=this.g;this.g=a;this.P("proxyStateChange",b,a);if(1==a)for(;!this.B.isEmpty();)g.lC(this.B).apply(this);else 3==a&&this.dispose()}};
g.h.nR=function(a,b){this.P(a,b)};
g.h.OO=function(a){if(!a)this.Cl(null),P7(this,null);else if(this.o.receiver.volume){a=this.o.receiver.volume;var b=R7(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)$6("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,T7(this,b)}};
g.h.Cl=function(a){$6("CP","Cast media: "+!!a);this.l&&this.l.removeUpdateListener(this.F);if(this.l=a)this.l.addUpdateListener(this.F),aCa(this),this.P("remotePlayerChange")};
g.h.NO=function(a){a?(aCa(this),this.P("remotePlayerChange")):this.Cl(null)};
g.h.bP=function(){var a=XBa();a&&P7(this,a)};
g.h.fc=function(a){$6("CP",a)};g.A(X7,g.EF);g.h=X7.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime;g.t(m)&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);f&&(l.clickTrackingParams=f);c&&(l.listId=c);g.t(k)&&(l.currentIndex=k);c&&(this.bb.listId=c);this.bb.videoId=d;this.bb.index=k||0;this.bb.state=3;L7(this.bb,m);this.A="UNSUPPORTED";Y7("Connecting with setPlaylist and params: "+g.wg(l));this.g.connect({method:"setPlaylist",params:g.wg(l)},a,wAa())}else Y7("Connecting without params"),
this.g.connect({},a,wAa());cCa(this)};
g.h.dispose=function(){this.ha()||(this.P("beforeDispose"),Z7(this,3));X7.Z.dispose.call(this)};
g.h.U=function(){$7(this);b8(this);a8(this);g.PD(this.H);this.H=window.NaN;g.PD(this.I);this.I=window.NaN;this.o=null;g.pF(this.V);this.V.length=0;this.g.dispose();X7.Z.U.call(this);this.A=this.D=this.l=this.bb=this.g=null};
g.h.fI=function(){this.C(2)};
g.h.SO=function(){Y7("Channel opened");this.N&&(this.N=!1,a8(this),this.L=g.ND((0,g.z)(function(){Y7("Timing out waiting for a screen.");this.C(1)},this),15E3));
AAa(mBa(this.g),this.X)};
g.h.PO=function(){Y7("Channel closed");(0,window.isNaN)(this.B)?l6(!0):l6();this.dispose()};
g.h.QO=function(a){l6();(0,window.isNaN)(this.F())?(Y7("Channel error: "+a+" without reconnection"),this.dispose()):(this.N=!0,Y7("Channel error: "+a+" with reconnection in "+this.F()+" ms"),Z7(this,2))};
g.h.RO=function(a){a.params?Y7("Received: action="+a.action+", params="+g.wg(a.params)):Y7("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=g.Xw(a.params.devices);this.l=(0,g.H)(a,function(a){return new $5(a)});
a=!!g.Ia(this.l,function(a){return"LOUNGE_SCREEN"==a.type});
fCa(this,a);break;case "loungeScreenDisconnected":g.Sa(this.l,function(a){return"LOUNGE_SCREEN"==a.type});
fCa(this,!1);break;case "remoteConnected":var b=new $5(g.Xw(a.params.device));g.Ia(this.l,function(a){return b?a.id==b.id:!1})||g.Pa(this.l,b);
break;case "remoteDisconnected":b=new $5(g.Xw(a.params.device));g.Sa(this.l,function(a){return b?a.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":hCa(this,a);break;case "nowPlaying":jCa(this,a);break;case "onStateChange":iCa(this,a);break;case "onAdStateChange":kCa(this,a);break;case "onVolumeChanged":lCa(this,a);break;case "onSubtitlesTrackChanged":gCa(this,a);break;case "nowAutoplaying":mCa(this,a);break;case "autoplayDismissed":this.P("autoplayDismissed");break;case "autoplayUpNext":this.D=a.params.videoId||null;this.P("autoplayUpNext",this.D);break;case "onAutoplayModeChanged":this.A=
a.params.autoplayMode;this.P("autoplayModeChange",this.A);"DISABLED"==this.A&&this.P("autoplayDismissed");break;case "onHasPreviousNextChanged":nCa(this,a);break;case "requestAssistedSignIn":this.P("assistedSignInRequested",a.params.authCode);break;default:Y7("Unrecognized action: "+a.action)}};
g.h.sT=function(){if(this.o){var a=this.o;this.o=null;this.bb.videoId!=a&&c8(this,"getNowPlaying")}};
X7.prototype.subscribe=X7.prototype.subscribe;X7.prototype.unsubscribeByKey=X7.prototype.Jd;X7.prototype.da=function(){var a=3;this.ha()||(a=0,(0,window.isNaN)(this.F())?V6(this.g)&&(0,window.isNaN)(this.B)&&(a=1):a=2);return a};
X7.prototype.getProxyState=X7.prototype.da;X7.prototype.C=function(a){Y7("Disconnecting with "+a);$7(this);this.P("beforeDisconnect",a);1==a&&l6();nBa(this.g,a);this.dispose()};
X7.prototype.disconnect=X7.prototype.C;X7.prototype.ca=function(){var a=this.bb;this.o&&(a=this.bb.clone(),N7(a,this.o,a.index));return O7(a)};
X7.prototype.getPlayerContextData=X7.prototype.ca;
X7.prototype.ka=function(a){var b=new I7(a);b.videoId&&b.videoId!=this.bb.videoId&&(this.o=b.videoId,g.PD(this.H),this.H=g.ND((0,g.z)(this.sT,this),5E3));var c=[];this.bb.listId==b.listId&&this.bb.videoId==b.videoId&&this.bb.index==b.index||c.push("remoteQueueChange");this.bb.g==b.g&&this.bb.volume==b.volume&&this.bb.muted==b.muted&&M7(this.bb)==M7(b)&&g.wg(this.bb.l)==g.wg(b.l)||c.push("remotePlayerChange");this.bb.reset(a);(0,g.C)(c,function(a){this.P(a)},this)};
X7.prototype.setPlayerContextData=X7.prototype.ka;X7.prototype.W=function(){var a=this.g.C.id,b=g.Ia(this.l,function(b){return"REMOTE_CONTROL"==b.type&&b.id!=a});
return b?b.id:""};
X7.prototype.getOtherConnectedRemoteId=X7.prototype.W;X7.prototype.F=function(){var a=this.g;return a.l.isActive()?a.l.l-(0,g.G)():window.NaN};
X7.prototype.getReconnectTimeout=X7.prototype.F;X7.prototype.Y=function(){return this.A||"UNSUPPORTED"};
X7.prototype.getAutoplayMode=X7.prototype.Y;X7.prototype.ba=function(){return this.D||""};
X7.prototype.getAutoplayVideoId=X7.prototype.ba;X7.prototype.oa=function(){if(!(0,window.isNaN)(this.F())){var a=this.g.l;g.au(a.g);a.start()}};
X7.prototype.reconnect=X7.prototype.oa;X7.prototype.fa=function(a,b){c8(this,a,b);eCa(this)};
X7.prototype.sendMessage=X7.prototype.fa;g.A(d8,d7);g.h=d8.prototype;g.h.ke=function(a){return this.dd.$_gs(a)};
g.h.contains=function(a){return!!this.dd.$_c(a)};
g.h.get=function(a){return this.dd.$_g(a)};
g.h.start=function(){this.dd.$_st()};
g.h.add=function(a,b,c){this.dd.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.dd.$_r(a,b,c)};
g.h.Dp=function(a,b,c,d){this.dd.$_un(a,b,c,d)};
g.h.U=function(){for(var a=0,b=this.l.length;a<b;++a)this.dd.$_ubk(this.l[a]);this.l.length=0;this.dd=null;d8.Z.U.call(this)};
g.h.KU=function(){this.P("screenChange")};
g.h.OQ=function(){this.P("onlineScreenChange")};
m7.prototype.$_st=m7.prototype.start;m7.prototype.$_gspc=m7.prototype.LU;m7.prototype.$_gsppc=m7.prototype.VD;m7.prototype.$_c=m7.prototype.contains;m7.prototype.$_g=m7.prototype.get;m7.prototype.$_a=m7.prototype.add;m7.prototype.$_un=m7.prototype.Dp;m7.prototype.$_r=m7.prototype.remove;m7.prototype.$_gs=m7.prototype.ke;m7.prototype.$_gos=m7.prototype.UD;m7.prototype.$_s=m7.prototype.subscribe;m7.prototype.$_ubk=m7.prototype.Jd;var e8=null,f8=null,u8=null,j8=[];g.p(v8,g.K);g.h=v8.prototype;
g.h.U=function(){g.K.prototype.U.call(this);this.A.stop();this.B.stop();this.K.stop();this.N();this.g.unsubscribe("proxyStateChange",this.IB,this);this.g.unsubscribe("remotePlayerChange",this.Fl,this);this.g.unsubscribe("remoteQueueChange",this.Qo,this);this.g.unsubscribe("autoplayUpNext",this.eB,this);this.g.unsubscribe("previousNextChange",this.FB,this);this.g.unsubscribe("nowAutoplaying",this.xB,this);this.g.unsubscribe("autoplayDismissed",this.dB,this);this.g=this.F=null};
g.h.iA=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.g.g)if(y8(this)){if(!R7(this.g).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":R7(this.g).kb()?this.g.pause():this.g.play();break;case "control_play":this.g.play();break;case "control_pause":this.g.pause();break;case "control_seek":this.I.pj(c[0],c[1]);break;case "control_subtitles_set_track":z8(this,c[0]);break;case "control_set_audio_track":c=c[0],y8(this)&&this.g.lv(this.l.ea(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.l.getCurrentTime();A8(this,0==c?void 0:c);break;case "control_seek":A8(this,c[0]);break;case "control_subtitles_set_track":z8(this,c[0]);break;case "control_set_audio_track":c=c[0],y8(this)&&this.g.lv(this.l.ea(1).videoId,c)}};
g.h.MO=function(a){this.K.bI(a)};
g.h.nU=function(a){this.iA("control_subtitles_set_track",g.Ub(a)?null:a)};
g.h.dD=function(){var a=this.l.zc("captions","track");g.Ub(a)||z8(this,a)};
g.h.vB=function(a){if(y8(this)){this.g.unsubscribe("remotePlayerChange",this.Fl,this);var b=Math.round(a.volume);a=!!a.muted;var c=R7(this.g);if(b!=c.volume||a!=c.muted)this.g.setVolume(b,a),this.L.start();this.g.subscribe("remotePlayerChange",this.Fl,this)}};
g.h.gQ=function(){g.Ub(this.C)||zCa(this,this.C);this.D=!1};
g.h.IB=function(a,b){this.B.stop();2==b&&this.aD()};
g.h.Fl=function(){if(y8(this)){this.A.stop();var a=R7(this.g);switch(a.g){case 1081:case 1:x8(this,new g.OO(8));this.ZC();break;case 1085:case 3:x8(this,new g.OO(9));break;case 1083:case 0:x8(this,new g.OO(2));this.I.stop();w8(this,this.l.ea().lengthSeconds);break;case 1084:x8(this,new g.OO(4));break;case 2:x8(this,new g.OO(4));w8(this,M7(a));break;case -1:x8(this,new g.OO(64));break;case -1E3:a={errorCode:"mdx.remoteerror",message:g.U("YTP_MDX_PLAYER_ERROR")},x8(this,new g.OO(128,a))}a=R7(this.g).l;
var b=this.C;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.format==b.format&&a.kind==b.kind:1)||(this.C=a,zCa(this,a));a=R7(this.g);-1==a.volume||Math.round(this.l.getVolume())==a.volume&&this.l.isMuted()==a.muted||this.L.isActive()||this.GD()}else yCa(this)};
g.h.FB=function(){this.l.P("mdxpreviousnextchange")};
g.h.Qo=function(){y8(this)||yCa(this)};
g.h.nH=function(){this.g.jx()};
g.h.eB=function(a){a&&(a=g.kE("/watch_queue_ajax",{method:"GET",Zc:{action_get_watch_queue_item:1,video_id:a},Hb:(0,g.z)(this.nS,this)}))&&(this.N=(0,g.z)(a.abort,a))};
g.h.nS=function(a,b){var c=new g.PN({videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.l.P("mdxautoplayupnext",c)};
g.h.xB=function(a){(0,window.isNaN)(a)||this.l.P("mdxnowautoplaying",a)};
g.h.dB=function(){this.l.P("mdxautoplaycanceled")};
g.h.RM=function(a,b){-1==R7(this.g).g?A8(this,a):b&&this.g.SD(a)};
g.h.GD=function(){if(y8(this)){var a=R7(this.g);this.o.Ba(this.V);a.muted?this.l.mute():this.l.Wf();this.l.setVolume(a.volume);this.V=this.o.O(this.l,"onVolumeChange",this.vB)}};
g.h.ZC=function(){this.A.stop();if(!this.g.ha()){var a=R7(this.g);a.kb()&&x8(this,new g.OO(8));w8(this,M7(a));this.A.start()}};
g.h.aD=function(){this.B.stop();this.A.stop();var a=this.g.A.getReconnectTimeout();2==this.g.g&&!(0,window.isNaN)(a)&&this.B.start()};g.p(B8,g.V);B8.prototype.A=function(a){BCa(this,a.state)};g.p(C8,g.JZ);C8.prototype.I=function(){var a=this.l.zc("remote","receivers");a&&1<a.length&&!this.l.zc("remote","quickCast")?(this.F=g.ib(a,this.B,this),g.KZ(this,(0,g.H)(a,this.B)),a=this.l.zc("remote","currentReceiver"),this.sf(this.B(a)),this.enable(!0)):this.enable(!1)};
C8.prototype.B=function(a){return a.key};
C8.prototype.rf=function(a){return"cast-selector-receiver"==a?g.U("YTP_MDX_CAST_SELECTOR"):this.F[a].name};
C8.prototype.td=function(a){g.JZ.prototype.td.call(this,a);this.l.Hd("remote","currentReceiver",this.F[a]);this.A.Ob()};g.p(D8,g.zV);g.h=D8.prototype;g.h.create=function(){sCa(g.jM(g.X(this.g)));this.C.push(g.PF("yt-remote-before-disconnect",this.IO,this));this.C.push(g.PF("yt-remote-connection-change",this.wR,this));this.C.push(g.PF("yt-remote-receiver-availability-change",this.GB,this));this.C.push(g.PF("yt-remote-auto-connect",this.uR,this));this.C.push(g.PF("yt-remote-receiver-resumed",this.tR,this));this.GB()};
g.h.load=function(){this.g.lt();g.zV.prototype.load.call(this);this.B=new v8(this,this.g,this.l);var a=(a=xCa())?a.currentTime:0;var b=t8()?new Q7(o8(),void 0):null;0==a&&b&&(a=M7(R7(b)));0!=a&&(this.H=a||0,this.g.P("progresssync",a,void 0));ACa(this,this.D,this.D);g.U_(this.g.app,6)};
g.h.unload=function(){this.g.P("mdxautoplaycanceled");this.A=this.o;g.Xe(this.B,this.l);this.l=this.B=null;g.zV.prototype.unload.call(this);g.U_(this.g.app,5)};
g.h.U=function(){g.QF(this.C);g.zV.prototype.U.call(this)};
g.h.ul=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.B.iA.apply(this.B,[].concat([a],g.pa(c)))};
g.h.XH=function(){return this.loaded?this.B.suggestion:null};
g.h.Lf=function(){return this.l?R7(this.l).Lf:!1};
g.h.hasNext=function(){return this.l?R7(this.l).hasNext:!1};
g.h.getCurrentTime=function(){return this.H};
g.h.FM=function(){var a=R7(this.l),b=this.g.ea();return{allowSeeking:this.g.ed(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.C?a.A+K7(a):a.A,isPeggedToLive:1>=(a.C?a.o+K7(a):a.o)-this.getCurrentTime(),loaded:a.I,seekableEnd:a.C?a.o+K7(a):a.o,seekableStart:0<a.B?a.B+K7(a):a.B}};
g.h.GM=function(){this.l&&this.l.QD()};
g.h.HM=function(){this.l&&this.l.RD()};
g.h.IO=function(a){1==a&&(this.I=this.l?R7(this.l):null)};
g.h.wR=function(){var a=t8()?new Q7(o8(),void 0):null;if(a){var b=this.A;this.loaded&&this.unload();this.l=a;this.I=null;b.key!=this.o.key&&(this.A=b,this.load())}else g.We(this.l),this.l=null,this.loaded&&(this.unload(),(a=this.I)&&a.videoId==this.g.ea().videoId&&this.g.Kz(a.videoId,M7(a)));this.g.P("videodatachange","newdata",this.g.ea(),3)};
g.h.GB=function(){this.F=[this.o].concat(uCa());var a=p8()||this.o;E8(this,a);this.g.sa("onMdxReceiversChange")};
g.h.uR=function(){var a=p8();E8(this,a)};
g.h.tR=function(){this.A=p8()};
g.h.EM=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.F;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?G7():E8(this,b)),this.loaded?this.A:this.o;case "quickCast":return 2==this.F.length&&"cast-selector-receiver"==this.F[1].key?(b&&G7(),!0):!1}};
g.h.IM=function(){V7(this.l,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.Wc=function(){return!1};g.fY.remote=D8;})(_yt_player);
