/*
 * JTurma.java
 *
 * Created on March 27, 2004, 11:34 PM
 */

package jturma;

import java.util.Observable;
import java.util.Observer;
import javax.swing.JFrame;

/**
 *
 * @author  José C. Campos
 */
public class JTurma extends JFrame implements Observer {
    
    private Turma turma;
    
    /** Creates new form JTurma */
    public JTurma() {
        initComponents();
        this.turma = new Turma();
        this.turma.addObserver(this);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jDialog2 = new javax.swing.JDialog();
        jDialog3 = new javax.swing.JDialog();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        numero = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        String[] notas = {"1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20"};
        nota_teorica = new javax.swing.JComboBox(notas);
        jLabel4 = new javax.swing.JLabel();
        nota_pratica = new javax.swing.JSlider();
        jLabel7 = new javax.swing.JLabel();
        media = new javax.swing.JProgressBar();
        adicionar_button = new javax.swing.JButton();
        consultar_button = new javax.swing.JButton();
        remover_button = new javax.swing.JButton();
        limpar_button = new javax.swing.JButton();
        sair_button = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        quantos = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        SairProgama = new javax.swing.JMenuItem();
        Help = new javax.swing.JMenu();

        org.jdesktop.layout.GroupLayout jDialog3Layout = new org.jdesktop.layout.GroupLayout(jDialog3.getContentPane());
        jDialog3.getContentPane().setLayout(jDialog3Layout);
        jDialog3Layout.setHorizontalGroup(
            jDialog3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 400, Short.MAX_VALUE)
        );
        jDialog3Layout.setVerticalGroup(
            jDialog3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 300, Short.MAX_VALUE)
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel1.setText("N�mero:");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel2.setText("Nome:");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel3.setText("Nota Te�rica:");

        nota_teorica.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        this.nota_teorica.setSelectedIndex(9);

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel4.setText("Nota Pr�tica:");

        nota_pratica.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        nota_pratica.setMajorTickSpacing(5);
        nota_pratica.setMaximum(20);
        nota_pratica.setMinorTickSpacing(1);
        nota_pratica.setPaintLabels(true);
        nota_pratica.setPaintTicks(true);
        nota_pratica.setSnapToTicks(true);
        nota_pratica.setValue(10);

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel7.setText("M�dia:");

        media.setMaximum(20);

        adicionar_button.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        adicionar_button.setText("Adicionar");
        adicionar_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionar_action(evt);
            }
        });

        consultar_button.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        consultar_button.setText("Consultar");
        consultar_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultar_action(evt);
            }
        });

        remover_button.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        remover_button.setText("Remover");
        remover_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remover_action(evt);
            }
        });

        limpar_button.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        limpar_button.setText("Limpar");
        limpar_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpar_action(evt);
            }
        });

        sair_button.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        sair_button.setText("Sair");
        sair_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sair_action(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel5.setText("Quantos passam?");

        quantos.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        quantos.setText("0");

        jMenu3.setText("File");

        SairProgama.setText("Sair ");
        SairProgama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairProgamaActionPerformed(evt);
            }
        });
        jMenu3.add(SairProgama);

        jMenuBar2.add(jMenu3);

        Help.setText("Help");
        Help.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HelpActionPerformed(evt);
            }
        });
        jMenuBar2.add(Help);

        setJMenuBar(jMenuBar2);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(8, 8, 8)
                                .add(jLabel7)
                                .add(33, 33, 33))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                .add(jLabel4)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)))
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(nota_pratica, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(layout.createSequentialGroup()
                                .add(jLabel5)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(quantos))
                            .add(layout.createSequentialGroup()
                                .add(6, 6, 6)
                                .add(media, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 172, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .add(36, 36, 36)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(limpar_button, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(sair_button, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(adicionar_button, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(consultar_button, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(remover_button, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 98, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(jLabel3)
                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 78, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 78, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(nota_teorica, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 78, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(nome, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 268, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(numero, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(numero, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(nome, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(nota_teorica, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                                .add(layout.createSequentialGroup()
                                    .add(9, 9, 9)
                                    .add(jLabel4)
                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .add(jLabel7))
                                .add(layout.createSequentialGroup()
                                    .add(nota_pratica, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                    .add(media, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                            .add(layout.createSequentialGroup()
                                .add(adicionar_button)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(consultar_button)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(remover_button)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(limpar_button)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(sair_button))))
                    .add(layout.createSequentialGroup()
                        .add(jLabel3)
                        .add(170, 170, 170)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel5)
                            .add(quantos))))
                .add(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void remover_action(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remover_action
        // Add your handling code here:
        String num = this.numero.getText();
        if (!num.equals("")) {
            try {
                this.turma.delAluno(num);
                this.limpar_action(evt);
            }
            catch (TurmaException a) {
                javax.swing.JOptionPane.showMessageDialog(this, "Aluno "+num+" não existe!\nPor favor indique um número de aluno válido.", "Aluno inexistente", 0);
            }
        }  else
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor indique um número de aluno.", "Dados incompletos", 0);
    }//GEN-LAST:event_remover_action

    private void consultar_action(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultar_action
        // Add your handling code here:
        String num = this.numero.getText();
        if (!num.equals("")) {
            try {
                Aluno a=this.turma.getAluno(num);
                
                this.nome.setText(a.getNome());
                this.nota_teorica.setSelectedItem(""+a.getNotaT());
                this.nota_pratica.setValue(a.getNotaP());
                this.media.setValue(a.getMedia());
            }
            catch (TurmaException a) {
                javax.swing.JOptionPane.showMessageDialog(this, "Aluno "+num+" não existe!\nPor favor indique um número de aluno válido.", "Aluno inexistente", 0);
            }
        }  else
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor indique um número de aluno.", "Dados incompletos", 0);
    }//GEN-LAST:event_consultar_action

    private boolean validaDados() {
        boolean vazio = this.numero.getText().equals("") || this.nome.getText().equals("");
        
        if (vazio)
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor preencha todos os dados.", "Dados incompletos", 0);
        
        return !vazio;
    }
    
    private void adicionar_action(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionar_action
        // Add your handling code here:
        if (this.validaDados()) {
            String num = this.numero.getText();
            String nome = this.nome.getText();
            int notaT = Integer.parseInt((String)this.nota_teorica.getSelectedItem());
            int notaP = this.nota_pratica.getValue();
            
            this.turma.addAluno(new Aluno(num, nome, notaT, notaP));
        }        
    }//GEN-LAST:event_adicionar_action

    private void limpar_action(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpar_action
        // Add your handling code here:
        this.nome.setText("");
        this.numero.setText("");
        this.nota_teorica.setSelectedIndex(9);
        this.nota_pratica.setValue(10);
        this.media.setValue(0);
    }//GEN-LAST:event_limpar_action

    private void sair_action(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sair_action
        // Add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_sair_action
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void SairProgamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairProgamaActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_SairProgamaActionPerformed

    private void HelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HelpActionPerformed
        // TODO add your handling code here:
        jDialog3.setVisible(true);
    }//GEN-LAST:event_HelpActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JTurma().setVisible(true);
            }
        });
    }
    
    /**
     * Método necessário para a interface Observer
     */
    public void update(Observable observable, Object obj) {
        this.quantos.setText(""+this.turma.quantosPassam());
    }    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Help;
    private javax.swing.JMenuItem SairProgama;
    private javax.swing.JButton adicionar_button;
    private javax.swing.JButton consultar_button;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JDialog jDialog3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JButton limpar_button;
    private javax.swing.JProgressBar media;
    private javax.swing.JTextField nome;
    private javax.swing.JSlider nota_pratica;
    private javax.swing.JComboBox nota_teorica;
    private javax.swing.JTextField numero;
    private javax.swing.JLabel quantos;
    private javax.swing.JButton remover_button;
    private javax.swing.JButton sair_button;
    // End of variables declaration//GEN-END:variables
    
}
